### ISSUE TITLE
想问问这个是什么意思

### ISSUE THREAD

**Issue by xihuanbodajingshen** [Plachtaa/VITS-fast-fine-tuning#10]
![image](https://user-images.githubusercontent.com/117348582/220279339-7b9627db-40c2-4690-820a-9c85e7d8542b.png)

**Comment by Plachtaa** [comment]
可能是上传的文件结构不对，可以把你的zip文件预览截个图看一下吗？

**Comment by xihuanbodajingshen** [comment]
> 可能是上传的文件结构不对，可以把你的zip文件预览截个图看一下吗？

这个好像确实是目录不对
