### ISSUE TITLE
运行步骤3步骤报错

### ISSUE THREAD

**Issue by birchday** [Plachtaa/VITS-fast-fine-tuning#101]
运行步骤3步骤报错   谢谢 佬
![11](https://user-images.githubusercontent.com/125856067/224532532-cad7e104-9ee3-4938-9ef9-a95294aadbfb.jpg)

 音频是用  STEP 2.1 上传短音频    上传选项1：运行该代码块会出现一个文件上传的入口
 
![33](https://user-images.githubusercontent.com/125856067/224532673-99a0d149-6584-4b5b-89f6-949d74195276.jpg)

![44](https://user-images.githubusercontent.com/125856067/224532753-f8f6887f-509d-4405-a263-5d6297308803.jpg)

**Comment by Plachtaa** [comment]
请参照[#16](https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/16)

**Comment by birchday** [comment]
谢谢 佬
谢谢分享
