### ISSUE TITLE
和人工标注训练的区别。

### ISSUE THREAD

**Issue by ysngki** [Plachtaa/VITS-fast-fine-tuning#105]
你好你好，阅读代码后，发现训练时需要用到的数据是在 segmented_character_voice 目录下的音频 以及 final_annotation_*.txt 用来提供索引和标注。项目中的标注以及切分似乎使用whisper来自动完成的，因此可能会导致效果不好。

如果我自己准备好人工切分的音频文件放到segmented_character_voice目录下面，并且自己标注，那是不是我这个训练就等同于有标注的fine-tuning了。

**Comment by ysngki** [comment]
（不好意思，刚才的表述有点不正确。似乎，实际上并不是所有的数据都存在 segmented_character_voice 目录下，这个目录只是用来存 long audio 的。重要的只有 final_annotation_*.txt ）

所以只要我自己切分好数据，然后将音频位置写在 txt 文件中，并且加上人工标注，那么我运行代码的话，实际上就是在做有标注的fine-tuning吗，也就是说质量有保证？

顺道有个小问题，我发现 short audio 好像没有去噪这一步，是因为他们不全是wav文件格式，所以不一定都能去噪吗？

**Comment by Plachtaa** [comment]
短音频去噪起来非常慢，所以懒得写了
你如果愿意自己标注，或者有现成标注可以用的话，当然是可以自行替换的

**Comment by ysngki** [comment]
谢谢回复，close。
