### ISSUE TITLE
add requirements_infer.txt

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#108]
只做推理用的话，能少安装哪些依赖
最近在安卓上使用linuxDeploy部署vits server，安装依赖这部分时间略长

**Comment by Plachtaa** [comment]
whisper和demucs都不用装，别的应该都少不了的。如果你不使用gradio当UI的话，gradio也可以踢了

**Comment by eve2ptp** [comment]
ok
