### ISSUE TITLE
运行exe程序报错闪退

### ISSUE THREAD

**Issue by DeanGeist** [Plachtaa/VITS-fast-fine-tuning#115]
![1679280739669](https://user-images.githubusercontent.com/128340641/226238566-432efc0e-e4af-4f8b-98e1-994ef0d69e7b.png)
训练后的模型文件和配置文件已按要求重命名并放在路径下，试了下同样的模型和文件在Moegoe里可以正常生成语音，大佬们救救

**Comment by Plachtaa** [comment]
config放错了，应该用1finetune_speaker.json1不是1moegoe_config.json1

**Comment by DeanGeist** [comment]
> 

遇到这个报错的时候文件名已经是finetune_speaker.json了，担心文件本身有问题所以用moegoe试了下

**Comment by Plachtaa** [comment]
不是文件名的问题，这两个文件的格式不一样，不是改个名字就能兼容的

**Comment by DeanGeist** [comment]
> 不是文件名的问题，这两个文件的格式不一样，不是改个名字就能兼容的

感谢大佬，用你做的模型和配置文件成功运行了！
