### ISSUE TITLE
字幕文件可以手动导入吗，不用whisper来识别字幕

### ISSUE THREAD

**Issue by kirbystudy** [Plachtaa/VITS-fast-fine-tuning#116]

**Comment by Plachtaa** [comment]
只需要在运行完STEP3，也就是切片之后，手动更改生成的long_character_anno.txt和short_character_anno.txt这两个文件里的标注就可以了。更改完毕后再运行STEP3.5

**Comment by kirbystudy** [comment]
好的感谢作者！

**Comment by kirbystudy** [comment]
请问一下这个库支持训练中文方言吗，训练出来的模型配合moegoe使用，发现说的声音和数据集的声音不太一样。

**Comment by Plachtaa** [comment]
方言不支持

**Comment by kirbystudy** [comment]
我看你的源代码里面有GD的

**Comment by Plachtaa** [comment]
但是没有对应的预训练模型。如果真的想训得从头开始训练，那就是另一回事了

**Comment by kirbystudy** [comment]
我看到这位作者的作品 https://huggingface.co/spaces/skytnt/moe-tts mode14 里面是有中文方言的

**Comment by Plachtaa** [comment]
他发布的只有Generator，如果要训练的话Generator和Discriminator都必须要有

**Comment by kirbystudy** [comment]
没找到他的预模型，只有预览模型

**Comment by kirbystudy** [comment]
你说的鉴别器是指这个吗 https://github.com/CjangCjengh/chinese-dialect-lexicons

**Comment by Plachtaa** [comment]
不是，是VITS的Discriminator模型参数，也就是`D_*.pth`

**Comment by kirbystudy** [comment]
好，如果有这个预模型就可以加进去了？

**Comment by Plachtaa** [comment]
还得改一些代码让它能兼容你找到的模型所对应的语言才行。目前只有中日英支持。你要是能找到G和D都有的模型的话我可以帮你加上去，

**Comment by Plachtaa** [comment]
额，不行

**Comment by kirbystudy** [comment]
还有预模型，可以包含其他的声音吗？

**Comment by Plachtaa** [comment]
https://github.com/CjangCjengh/vits

**Comment by kirbystudy** [comment]
一般预训练的话，训练步数要调整多少好。

**Comment by Plachtaa** [comment]
至少80万步吧

**Comment by kirbystudy** [comment]
训练多少轮取决于实际的数据集内容数量，那来这么多数据集

**Comment by kirbystudy** [comment]
![image](https://user-images.githubusercontent.com/63231787/227089332-ef2a766d-bfe8-491c-a19c-48d4945c0109.png)
我看这里有说明的

**Comment by Plachtaa** [comment]
原论文就是256的batch size在一万多条的数据集上训练了80万步的，我自己训的模型也基本是到80万步才能用，具体训多久你自己决定吧

**Comment by kirbystudy** [comment]
256的batch size 是什么意思

**Comment by kirbystudy** [comment]
训练了80万步 不是一次性吧，每天重复训练这样子吗

**Comment by Plachtaa** [comment]
从头开始训练的话，在一张3090上大概需要一到两个星期吧

**Comment by kirbystudy** [comment]
如果在colab训练呢，我训练的是单个模型。

**Comment by Plachtaa** [comment]
colab从头开始训练有点天方夜谭了，首先你每天只能训练几个小时就会被掐掉，其次免费的T4卡速度不太理想。除非你愿意给colab充钱

**Comment by kirbystudy** [comment]
> 从头开始训练的话，在一张3090上大概需要一到两个星期吧

没这么好的显卡，只能在colab上训练了，顺便一提，如果单个模型训练 colab pro 要多少个计算单元

**Comment by Plachtaa** [comment]
T4一小时消耗是一点几，将近两个单元，如果训练100小时就要200个计算单元，大概150rmb吧，300rmb应该可以训一个比较好的

**Comment by kirbystudy** [comment]
> https://github.com/CjangCjengh/vits

你说的这个链接怎么在colab运行
一个是 [colab.ipynb](https://github.com/CjangCjengh/vits/blob/main/colab.ipynb)
另一个是 https://github.com/CjangCjengh/vits/blob/main/inference.ipynb
里面好像没有生成模型的配置文件

**Comment by Plachtaa** [comment]
不知道，我不推荐在colab上训练VITS这种需要按天计算时间的训练，我也不理解为什么原作者要写个colab笔记本，所以你最好去问原作者。

**Comment by kirbystudy** [comment]
原作者联系不上，我已经开始训练粤语模型了，我先跑800轮后再看看。

**Comment by kirbystudy** [comment]
cantonese 预模型训练完毕，训练步数是10w+ ,效果还不错，你看是否添加到脚本中。

**Comment by Plachtaa** [comment]
> cantonese 预模型训练完毕，训练步数是10w+ ,效果还不错，你看是否添加到脚本中。

好的，非常感谢你训练的模型，但是有一个问题是cantonese没有合适的自动标注工具，所以添加到这个项目里恐怕有些困难😢

**Comment by kirbystudy** [comment]
没有自动标注或许可以手动标注,目前来说没多少人用到这个预模型。

**Comment by kirbystudy** [comment]
预模型我上传到huggingface，你可以再这里下载。
https://huggingface.co/xiaomaiiwn/vits-cantonese/tree/main/model

**Comment by Plachtaa** [comment]
好的，感谢你的工作

**Comment by Plachtaa** [comment]
我刚刚看了一下，如果你的模型说话人只有一个的话，那这个模型对新的声线泛化能力是很差的。之前有试过用标贝单女声训练的纯中文模型进行微调，训练出来的男声完全是电音，你这个也是同理。所以虽然感到很抱歉，但是这个模型应该是不能加入到脚本中去的😢

**Comment by kirbystudy** [comment]
没考虑到男声的方面，确实有多个声线才能确保训练质量。没事，后面我接着训练。
