### ISSUE TITLE
update requirements.txt

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#117]
[Deprecation of CUDA 11.6 and Python 3.7 Support](https://pytorch.org/blog/deprecation-cuda-python-support/)
![image](https://user-images.githubusercontent.com/42791572/226619793-dddddb34-1900-47ca-a27e-b9a6ab32655e.png)

**Comment by Plachtaa** [comment]
感谢提醒，已去除torch的版本指定
