### ISSUE TITLE
处理长音频时报错

### ISSUE THREAD

**Issue by misss520** [Plachtaa/VITS-fast-fine-tuning#119]
Traceback (most recent call last):
  File "/content/VITS-fast-fine-tuning/long_audio_transcribe.py", line 46, in <module>
    code = file.rstrip(".wav").split("_")[1]
IndexError: list index out of range

文件格式 22050采样率的WAV音频文件，时长8分钟
在我手动切割后，上传短音频进行处理也发生了报错

**Comment by Plachtaa** [comment]
你这个报错大概率是文件名格式不对，看看文件名

**Comment by misss520** [comment]
![捕获](https://user-images.githubusercontent.com/80108847/227471517-1e9802ed-4610-4304-aabd-ce778dcbc303.PNG)

**Comment by misss520** [comment]
![捕获2](https://user-images.githubusercontent.com/80108847/227472275-093ae285-e83c-4894-b9c0-facaaf8fbe0b.PNG)

**Comment by Plachtaa** [comment]
请阅读数据格式要求
