### ISSUE TITLE
Windows下本地部署训练时出现size mismatch for enc_p.emb.weight错误

### ISSUE THREAD

**Issue by Suwanwa** [Plachtaa/VITS-fast-fine-tuning#123]
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/76982535/227715058-6f967981-0b3c-483c-a351-3044ca460ba4.png">
根据CSDN的[这篇文章](https://blog.csdn.net/weixin_44966641/article/details/120083303)对代码做了修改，但依旧报错（

**Comment by Plachtaa** [comment]
`cleaner`名字不对，要和预训练模型一致才行

**Comment by Suwanwa** [comment]
> 
QAQ大佬我预训练模型就是这个名字的呀
![image](https://user-images.githubusercontent.com/76982535/227717498-6169efd4-8509-42cf-8566-788979f13d3c.png)

**Comment by Plachtaa** [comment]
我指的是config文件里`text_cleaners`的名字

**Comment by Suwanwa** [comment]
> 

![image](https://user-images.githubusercontent.com/76982535/227718604-3f627d89-03d5-4c6b-b96b-90990d2c0889.png)
是这样嘛？还是一样的错误）

**Comment by Plachtaa** [comment]
把INFO第三行的`"text_cleaners"`从`"chinese_cleaners"`改成`"cjke_cleaners2"`
还有你这个config文件从哪来的，为什么cleaner名字都不对了

**Comment by Suwanwa** [comment]
> 把INFO第三行的`"text_cleaners"`从`"chinese_cleaners"`改成`"cjke_cleaners2"` 还有你这个config文件从哪来的，为什么cleaner名字都不对了

我知道了！刚才用colab重新跑了一下发现可能是我没运行python preprocess_v2.py --add_auxiliary_data True --languages CJ，这个config是在跑模型的时候模型目录中生成的，不过我运行python preprocess_v2.py --add_auxiliary_data True --languages CJ会报Traceback (most recent call last):
  File "E:\AI\VITS\VITS-Fast\preprocess_v2.py", line 30, in <module>
    path, speaker, text = line.split("|")
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by Plachtaa** [comment]
你要不现在colab里熟悉一下顺序，要是有什么bug可以整个IDE一行一行找，训练AI最麻烦的无非就是把数据集排列好，colab的目的就是为了按顺序自动处理，自己本地搞当然折磨
