### ISSUE TITLE
base模型推理效果

### ISSUE THREAD

**Issue by shandong-jiaotong** [Plachtaa/VITS-fast-fine-tuning#129]
你好，下载你的base G_0.pth模型，直接推理，发现效果很不好，读不清楚，请问是什么问题呢？用这个base模型进行克隆效果也不好。

**Comment by Plachtaa** [comment]
1. huggingface在README里有贴链接
2. 维度不一致说明你自己初始化的模型和你load的模型支持的语言不一致，自己检查一下设置
3. 这是为了把其它语言和中文写进一个unified的cleaners，这个我是搬的别人的，我不是很清楚
4. 有，但是不是通过转罗马音实现的

**Comment by Plachtaa** [comment]
Close this issue due to long time of no reply
