### ISSUE TITLE
跑了25个epoch 声音非常糊

### ISSUE THREAD

**Issue by Liuxc2005** [Plachtaa/VITS-fast-fine-tuning#13]
请问如果音源有一点点噪音（几段音源有声音很小的bgm）的话是不是就会这样？

**Comment by Plachtaa** [comment]
声音糊的问题我之前也遇到过几例，和角色的声线以及样本质量都有关。如果声音文件样本中什么话也没说的时长占比比较高的话，这种现象就会尤其严重。

**Comment by Liuxc2005** [comment]
哦哦，这样啊，谢谢！我试试把空白部分截掉吧。

**Comment by Plachtaa** [comment]
pipeline更新之后添加了对所有音频去背景音和自动切片并忽略空白段的内容，你可以用新的笔记本试试
