### ISSUE TITLE
step3 4报错 大佬请问一下是什么原因 

### ISSUE THREAD

**Issue by milli121** [Plachtaa/VITS-fast-fine-tuning#131]
step3报错 大佬请问一下是什么原因 我看了其他遇到同样问题的问答还有你的 但是还是解决不了

这是step3末尾

en not supported, ignoring...

transcribing ./denoised_audio/male_50989.wav...

en not supported, ignoring...

transcribing ./denoised_audio/milli_227698.wav...

en not supported, ignoring...

Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

这是step4

AssertionError                            Traceback (most recent call last)

[/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/preprocess_v2.py](https://localhost:8080/#) in <module>
     31         if speaker not in speakers:
     32             speakers.append(speaker)
---> 33     assert (len(speakers) != 0), "No audio file found. Please check your uploaded file structure."
     34     # Source 3 (Optional): sampled audios as extra training helpers
     35     if args.add_auxiliary_data:

AssertionError: No audio file found. Please check your uploaded file structure.

看了类似的问题反反复复按操作处理了还是一直这样报错
实在解决不了
求教大佬

**Comment by Plachtaa** [comment]
你训练的是英语吗？

**Comment by milli121** [comment]
对啊大佬，三个都是英语



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月29日 21:28 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Plachtaa/VITS-fast-fine-tuning] step3 4报错 大佬请问一下是什么原因  (Issue #131) |

你训练的是英语吗？

**Comment by milli121** [comment]
视频链接什么的也符合要求 就是全都是英语 只上传视频链接 短音频长音频还有视频都没上传 难道是这个的原因吗

**Comment by milli121** [comment]
在哪里改请问

**Comment by milli121** [comment]
哦已经看到了多谢大佬我先再试试我的错没有仔细看到描述

**Comment by codewen77** [comment]
> 你的训练样本是英语吗？

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/48975863/aeccb61d-7cd3-431e-85d8-13151ec90dfe)
请问怎么解决这个问题呀，期待您的回复
