### ISSUE TITLE
copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([78, 192])报错

### ISSUE THREAD

**Issue by IcedLimeTea** [Plachtaa/VITS-fast-fine-tuning#136]
想在GPU云服务器上训练一下，但是一直报这个错误，前面的步骤跟着jupyter上做完了，大佬请问这是什么原因？
![image](https://user-images.githubusercontent.com/113658584/228994383-bd08dacf-3dba-45f7-99a5-0a358f21dac6.png)

**Comment by Plachtaa** [comment]
vocabulary size不对，说明你初始化的模型所支持的语言和你load的预训练模型支持的语言不一致
