### ISSUE TITLE
Is it possible to train other Language?

### ISSUE THREAD

**Issue by ardha27** [Plachtaa/VITS-fast-fine-tuning#137]
Hello, i'm from Indonesia. Is it possible to train in Indonesian? If it's possible what do i need?

**Comment by Plachtaa** [comment]
Of course you can. The VITS model understands symbols (phonemes) only, so what you need to do is to design a function to convert raw Indonesian sentences to phoneme sequences, where each phoneme should from a pre-defined fixed-sized vocab (like what NLP does).

**Comment by ardha27** [comment]
sorry, can you give me reference how to that? or maybe example in other language. I'm not so familiar with VITS and NLP, thank you

**Comment by Plachtaa** [comment]
The source code of VITS model is rather simple, also you can find their original paper by googling. I believe it won't take long to figure it out by yourself. Here's the original repo: https://github.com/jaywalnut310/vits

**Comment by ardha27** [comment]
Thank you
