### ISSUE TITLE
试图采用本地训练时在“分割并标注长音频”处报错NameError: name 'lang2token' is not defined

### ISSUE THREAD

**Issue by unicorn5514** [Plachtaa/VITS-fast-fine-tuning#140]
我安装笔记本的命令和代码试图在本地进行相应的训练，前面都很顺利，但是在进行到“分割并标注长音频”时发生了报错，具体如下：
D:\text\VITS-fast-fine-tuning>python long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
transcribing ./denoised_audio/unicorn_0.wav...

Traceback (most recent call last):
  File "D:\text\VITS-fast-fine-tuning\long_audio_transcribe.py", line 41, in <module>
    if result['language'] not in list(lang2token.keys()):
NameError: name 'lang2token' is not defined

D:\text\VITS-fast-fine-tuning># 标注短音频
'#' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\text\VITS-fast-fine-tuning>python long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
transcribing ./denoised_audio/Unicorn_234135.wav...

Traceback (most recent call last):
  File "D:\text\VITS-fast-fine-tuning\long_audio_transcribe.py", line 41, in <module>
    if result['language'] not in list(lang2token.keys()):
NameError: name 'lang2token' is not defined

D:\text\VITS-fast-fine-tuning>python long_audio_transcribe.py --languages "{PRETRAINED_MODEL}" --whisper_size large
transcribing ./denoised_audio/Unicorn_234135.wav...

Traceback (most recent call last):
  File "D:\text\VITS-fast-fine-tuning\long_audio_transcribe.py", line 41, in <module>
    if result['language'] not in list(lang2token.keys()):
NameError: name 'lang2token' is not defined

这是由于什么原因引起的呢？

**Comment by unicorn5514** [comment]
我用相同的文件上传到笔记本中是能够正常运行的

**Comment by Plachtaa** [comment]
`PRETRAINED_MODEL`在Google Colab里是一个在STEP1.5定义过的变量，你在命令行窗口使用的时候就不能这么输入了

**Comment by Plachtaa** [comment]
Close this issue due to long time of no reply

**Comment by Json0926** [comment]
`python scripts/long_audio_transcribe.py --languages "{CJ}" --whisper_size large`

不是PRETRAINED_MODEL的问题吧 我使用的CJ输入还是会出现name 'lang2token' is not defined的问题， 是哪个版本的错误吗
