### ISSUE TITLE
STEP2.1 通过Google Drive上传短音频文件时出错

### ISSUE THREAD

**Issue by kamen-kkr** [Plachtaa/VITS-fast-fine-tuning#152]
求助：今天下午在上传Google Drive文件
ZIP_PATH：“/content/drive/MyDrive/Sample.zip”或者“../drive/MyDrive/Sample.zip”

发现报错：
cp: cannot create regular file './custom_character_voice/custom_character_voice.zip': No such file or directory
（上午及昨天，该文件路径格式均能成功识别文件并处理标签）
其中云盘文件结构如下：
├─drive
├   ├─MyDrive
├   ├   ├─Sample.zip

压缩包文件结构如下：
Sample.zip
├─character_1
├   ├─xxx.wav
├   ├─yyy.wav
├   ├─...

求大佬指点解决/(ㄒoㄒ)/~~

**Comment by Plachtaa** [comment]
这个文件格式看起来是没有问题的，但是也有可能是别的问题导致报错。建议重启会话之后用提供的样本数据试一下，看看是数据问题还是其它问题

**Comment by kamen-kkr** [comment]
/(ㄒoㄒ)/~~谢谢大佬，可能是昨天下午Google Drive抽风了，昨晚后来同样的引用目录就没问题了
我尝试了只单个角色外面不套文件夹，或者原readme中数据格式，均能上传成功。
（还有按步骤一步一步来，直接运行导入云盘数据那一步，可能出错了）
现在项目可正常运行，感谢大佬

**Comment by mikamijpen** [comment]
终于，单人的把外面的文件夹去掉就行了。
