### ISSUE TITLE
如何能选择和自己需要微调的角色相似的预训练角色？

### ISSUE THREAD

**Issue by linxiaolongwoai** [Plachtaa/VITS-fast-fine-tuning#155]

**Comment by Plachtaa** [comment]
训练的时候默认是把所有的speaker_embedding都删除，然后初始化新的speaker_embedding。如果你的角色声线和原模型里的某个角色很相似的话，新的speaker_embedding很快就会收敛到合适的值

**Comment by Plachtaa** [comment]
Close this issue due to long time of no reply
