### ISSUE TITLE
unzip:  cannot find or open  

### ISSUE THREAD

**Issue by Deeper-wk** [Plachtaa/VITS-fast-fine-tuning#16]
![A6ZG`{F29U2E(J88$5J{PTC](https://user-images.githubusercontent.com/85387275/220819055-fcb159b1-214a-409d-852f-f03d5cb1a179.png)
大佬，我不是很懂github，我尝试问个我不太懂的
我上传结构就是压缩包  压缩包里就一个文件夹放着对应的语音   结构是  压缩包/文件夹a/多个语音
但是我上传会  unzip:  cannot find or open  
![VJD$1CWEQW3$JR)SI KD57Q](https://user-images.githubusercontent.com/85387275/220819675-e26d0c70-3b81-493a-8e02-2ce4ad881a72.png)
wo我不是很懂，问问大佬:(

**Comment by Plachtaa** [comment]
只能传zip，rar是解不出来的

**Comment by Deeper-wk** [comment]
谢谢！非常感谢！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月23日(星期四) 中午12:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Plachtaa/VITS-fast-fine-tuning] unzip:  cannot find or open   (Issue #16)





 
只能传zip，rar是解不出来的
