### ISSUE TITLE
Colab配置环境报错 似乎与pyopenjtalk有关

### ISSUE THREAD

**Issue by 7ippo** [Plachtaa/VITS-fast-fine-tuning#164]
![image](https://user-images.githubusercontent.com/18611554/231051221-c2d93c6e-76cd-47be-9e1b-e2ab5083ce1c.png)
昨天4.10号训练过一次正常，今早重新用Colab就出问题，应该是一些包特定版本的问题？
断在了安装requirement里的pyopenjtalk，从jamo开始后续demucs gradio等包都没装上。

**Comment by Sandboxcn** [comment]
我也是

> ![image](https://user-images.githubusercontent.com/18611554/231051221-c2d93c6e-76cd-47be-9e1b-e2ab5083ce1c.png) 昨天4.10号训练过一次正常，今早重新用Colab就出问题，应该是一些包特定版本的问题？ 断在了安装requirement里的pyopenjtalk，从jamo开始后续demucs gradio等包都没装上。

**Comment by Alphastory17** [comment]
这是 pip 的问题，将 pip 降级为 21.3.1 即可解决。

**Comment by Plachtaa** [comment]
参照@icebear12138的建议(#165 )对`requirements.txt`进行了修改，经测试现在可以正常训练了
