### ISSUE TITLE
Colab配置环境依赖版本不兼容问题(pyopenjtalk,librosa)

### ISSUE THREAD

**Issue by icebear12138** [Plachtaa/VITS-fast-fine-tuning#165]
1.pyopenjtalk安装报错.实测使用0.1.3版本可用
    !pip install pyopenjtalk==0.1.3

2.librosa模块训练时报错:  TypeError: mel() takes 0 positional arguments but 5 were given.卸载librosa安装0.9.2版本可用:
    !pip uninstall librosa
    !pip install librosa==0.9.2

**Comment by Plachtaa** [comment]
感谢提醒，会及时开始修复

**Comment by Plachtaa** [comment]
按照你的建议对`requirements.txt`进行了修改，经测试现在可以正常训练了
