### ISSUE TITLE
长句子拆分有问题，不准确 

### ISSUE THREAD

**Issue by SpencerZhaoQi** [Plachtaa/VITS-fast-fine-tuning#168]
大佬，长句子拆分的地方是按秒来计算的，一秒内可能跨句子了，最终拆分下来不太准确

**Comment by Plachtaa** [comment]
whisper有时候确实是会抽风，但是大多数情况下是没问题的，而且那个拆分其实是按毫秒

**Comment by SpencerZhaoQi** [comment]
>         for i, seg in enumerate(result['segments']):
            start_time = seg['start']
            end_time = seg['end']
            text = seg['text']
            text = lang2token[lang] + text.replace("\n", "") + lang2token[lang]
            text = text + "\n"
            wav_seg = wav[:, int(start_time * sr):int(end_time) * sr)]
            wav_seg_name = f"{character_name}_{code}_{i}.wav"
            savepth = save_dir + character_name + "/" + wav_seg_name
            speaker_annos.append(savepth + "|" + character_name + "|" + text)
            print(f"Transcribed segment: {speaker_annos[-1]}")
            # trimmed_wav_seg = librosa.effects.trim(wav_seg.squeeze().numpy())
            # trimmed_wav_seg = torch.tensor(trimmed_wav_seg[0]).unsqueeze(0)
            torchaudio.save(savepth, wav_seg, 22050, channels_first=True)

我看这段代码，wav_seg = wav[:, int(start_time * sr):int(end_time) * sr)]。计算seg的时候用的是start_time和end_time，我断点跟了下，这两个时间都是秒，很奇怪，难道我有啥参数没有设置吗，按说代码没有动

**Comment by Plachtaa** [comment]
噢，抱歉，那应该是我记错了。如果是这样那确实有些地方可能不准，但是总体来说影响不大。
我也不太清楚有什么更好的切片方式，如果你知道的话希望可以提供一些建议，感谢

**Comment by SpencerZhaoQi** [comment]
啊，我解决了，果然有一个transcribe的参数可以指定segments返回对应的毫秒数（word_timestamps=True），默认是秒。
        result = model.transcribe(parent_dir + file, word_timestamps=True, **transcribe_options)
感谢提供思路哈哈，这样就非常准确了

**Comment by Plachtaa** [comment]
已修改该部分代码，感谢你提供解决方案
