### ISSUE TITLE
运行inference时报错

### ISSUE THREAD

**Issue by windbroker** [Plachtaa/VITS-fast-fine-tuning#17]
![QQ截图20230223220553](https://user-images.githubusercontent.com/120333252/220931145-3f2fdfc6-e1d1-444a-85e8-79c5bee09294.png)
我下载了模型文件和配置文件并且都改名放在了同一目录下，确定没有中文和空格，但还是报错
![QQ截图20230223220939](https://user-images.githubusercontent.com/120333252/220931401-7cd28766-4cd6-475c-b93b-6097e501e4f9.png)

**Comment by Plachtaa** [comment]
您好，感谢反馈！可以把你的finetune_speaker.json和G_latest.pth上传一下吗？我在本地测试一下

**Comment by windbroker** [comment]
好的，我是在b站看到的一个模型，他没有传配置文件所以我又去要了一份配置文件，这个应该没有什么所有权问题吧，作者也是直接发在简介的，上传的后缀改json，模型文件667MB超过限制了
[finetune_speaker.zip](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10814771/finetune_speaker.zip)

**Comment by Plachtaa** [comment]
他的配置文件有问题，他把symbols都删了，所以本地应用读不出来

**Comment by windbroker** [comment]
好的，感谢解答，我去问问作者




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Plachtaa/VITS-fast-fine-tuning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月23日(星期四) 晚上10:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Plachtaa/VITS-fast-fine-tuning] 运行inference时报错 (Issue #17)





 
他的配置文件有问题，他把symbols都删了，所以本地应用读不出来
