### ISSUE TITLE
关于ADD_AUXILIARY作用的讨论

### ISSUE THREAD

**Issue by 7ippo** [Plachtaa/VITS-fast-fine-tuning#172]
提问前先感谢作者编写的自动化脚本、分享和无私的解答，这极大降低了VITS的训练门槛。我想请教下关于ADD_AUXILIARY的作用，如果我样本数量50个左右，都手动校对过标注了（校对的是long_character_anno.txt和short_character_anno.txt这两个文件）。底模用的CJ那个，我是否还需要ADD_AUXILIARY注入预训练集里的数据呢，是否这样会导致训练效果反而较差？这个注入仅仅是为了增加样本量加速收敛，还有避免whisper标注的错误导致映射问题是吗，我这样理解正确吗？

另外我看colab笔记里在ADD_AUXILIAR那一步做了这个注释：
`# assert(not (ADD_AUXILIARY and PRETRAINED_MODEL != "CJE")), "add auxiliary data is available only available for CJE model!"`
但是好像已经增加了对CJ底模的支持，应该可以remove了。

除此之外我还有一个问题，就是如果选择了CJ作为底模，似乎下载的是[这里](https://huggingface.co/spaces/zomehwh/vits-uma-genshin-honkai/tree/main/model)的`D_0-p.pth`和`G_0-p.pth`，我能否用同路径下的`D_0.pth`和`G_0.pth`替换呢，如果可以，是否还要修改`config.json`？似乎那两个模型更大，不知是否对中文合成效果更有帮助。

![image](https://user-images.githubusercontent.com/18611554/231442659-ac8ea651-ccbe-4566-89bd-e7092914d5ee.png)

再次感谢作者。

**Comment by Plachtaa** [comment]
`ADD_AUXILIARY`的作用单纯就是缓解whisper标注错误带来的映射问题，这个在标注不准确的情况下是非常有帮助的，至少训练出来的新角色能够正常说话，如果你的标注没问题确实可以不勾选，训练会快一些。不过勾选了也不会有什么影响；
`G_0.pth`和`G_0-p.pth`是没有区别的，多出来的file size单纯是因为optimizer的梯度没有清除，整个模型参数就是160MB左右

**Comment by 7ippo** [comment]
谢谢，我看到SayaSS的[demo](https://huggingface.co/spaces/zomehwh/vits-uma-genshin-honkai)有特别多的speakers，如果我本地的推理inference那个打包路径下想用他训练好的模型看效果，请问是用哪个文件呢，也是将`G_0-p.pth`改名成`G_latest.pth`是吗？

**Comment by Plachtaa** [comment]
他那个config的格式只能用MoeGoe读取，inference-webui读取不了

**Comment by 7ippo** [comment]
好的，谢谢~上午我用370多个中文短音频+手动修复标注+不勾选ADD_AUXILIARY+100Epochs训练的中文合成效果很不错:smile:
但是句内一些训练样本里没有的英文是说不出来的，这个有什么办法吗？我看很多up主的嘴替里遇到英文单词也会说不出来，似乎是一个很常见的问题。我用的CJ底模，用CJE那个是否可以解决呢？

**Comment by Plachtaa** [comment]
CJ当然是不会说英文的，CJE才能说英文

**Comment by 7ippo** [comment]
了解了，谢谢作者~:grinning:
