### ISSUE TITLE
A discord server for discussion?

### ISSUE THREAD

**Issue by himekifee** [Plachtaa/VITS-fast-fine-tuning#179]
Hi. Much appreciated for all the work you have done. I did fine-tune my model and got a usable tts bot for my own discord server. Just wondering do you have any intention to create a Discord server for discussing problems or further improvement for the model? I'm not an expert in the field so I'd like to talk with people to share ideas and learn from them. If you don't want to operate a server, do you mind me putting an invitation link here? Thanks.

**Comment by Plachtaa** [comment]
Hi, I'm glad that you find this repo helpful. I apologize that currently I have no plan to create any discussion group or make any big updates, because I'm quite busy with my curriculums. If you wish, feel free to put the discord server link here or in README. Thanks!
