### ISSUE TITLE
正确的加dummy的方式

### ISSUE THREAD

**Issue by Accelsnow** [Plachtaa/VITS-fast-fine-tuning#182]
运行环境：win11 + ubuntu WSL 本地训练/推理
我的训练集大概有1500个单说话人日文干声素材，手动transcribe过

本地环境是搭好了的，用AUX可以正常训练，也可以推理，但是我想试一下不适用AUX的单说话人训练。我看issue和README里面都有提到加dummy也可行，但是我尝试了一下手动增加1-5个dummy，训练文件我给每个dummy新创了文件夹，文件用的就是主说话人的一个小子集，训练/验证文件表以及config都一一照着AUX的模式配置好了，训练的时候显示的配置也有所有说话人的name-id，speaker数量也是对的，但是还是会报 divide/mod by zero的错误。不知道是不是dummy有什么特殊的配置方法还是我有哪一步做错了。

**Comment by Qilely** [comment]
请问一下您1500条数据出现过训练基本没效果的情况吗？我是一个角色的语音分成了两个，一个主要的1600多条，一个效果不好的100多条作为“第二个角色”，结果训练后发现前者基本没有效果，即使是600epoch 也没啥效果，但后者就没问题….请问您的正常吗

**Comment by Accelsnow** [comment]
> 

我后面稍微精简了一下数据集，1100多条的时候我单speaker没有AUX没有dummy也可以训练了，不太清楚具体是怎么判定的。

我现在的数据集不是whisper自动标注的。我的音源有对应的字幕，所以我直接匹配了字幕文本。但是我这个字幕原版存在标点符号使用不是很准确的情况，比如不需要停顿的时候有顿号，以及过多的省略号。这个对我的模型质量有很大的影响。我手动修正这些问题之后训练结果还是很满意的（700epoch）。

**Comment by Qilely** [comment]
> > 请问一下您1500条数据出现过训练基本没效果的情况吗？我是一个角色的语音分成了两个，一个主要的1600多条，一个效果不好的100多条作为“第二个角色”，结果训练后发现前者基本没有效果，即使是600epoch 也没啥效果，但后者就没问题….请问您的正常吗
> 
> 我后面稍微精简了一下数据集，1100多条的时候我单speaker没有AUX没有dummy也可以训练了，不太清楚具体是怎么判定的。
> 
> 我现在的数据集不是whisper自动标注的。我的音源有对应的字幕，所以我直接匹配了字幕文本。但是我这个字幕原版存在标点符号使用不是很准确的情况，比如不需要停顿的时候有顿号，以及过多的省略号。这个对我的模型质量有很大的影响。我手动修正这些问题之后训练结果还是很满意的（700epoch）。

在没有dummy和aux的情况下没有报错吗？我尝试过不加aux，然后就像我回复那样又加了一个，但还是报错
