### ISSUE TITLE
pip依赖安装问题

### ISSUE THREAD

**Issue by nekomiya-hinata** [Plachtaa/VITS-fast-fine-tuning#188]
仓库最新版本的pip依赖，在python3.10环境下安装会报错：ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

**Comment by Plachtaa** [comment]
把python降级到3.8试试

**Comment by nekomiya-hinata** [comment]
> 把python降级到3.8试试

应该是旧版本的numpy在python3.10中没有构建文件的原因，降级就好了
