### ISSUE TITLE
本地部署后使用日语时报错

### ISSUE THREAD

**Issue by spicytaoki** [Plachtaa/VITS-fast-fine-tuning#19]
在colab上进行微调后本地部署使用，中文与英语正常，但是使用日语时会报错。
![屏幕截图 2023-02-24 211637](https://user-images.githubusercontent.com/32639651/221188296-262af8bf-3c62-4ddd-8655-654fd8d69e1b.png)

**Comment by vic233333** [comment]
同样的问题

**Comment by spicytaoki** [comment]
> 同样的问题

已解决，将open_jtalk_dic_utf_8-1.11下载后解压放入pyopenjtalk文件夹中即可。
