### ISSUE TITLE
在你的底膜上自己微调，可以商用吗？

### ISSUE THREAD

**Issue by bhj8** [Plachtaa/VITS-fast-fine-tuning#193]
底膜有点难搞，用你的底膜，自己的搞数据进行快速微调出来的模型，可以商用吗？

**Comment by Plachtaa** [comment]
当然可以。作为开发者而言，如果你觉得训练出来的模型能达到商用标准，那毫无疑问是对该项目的最高认同，我由衷地感到高兴。

**Comment by bhj8** [comment]
谢谢你~！
