### ISSUE TITLE
Chinese TTS generation error using latest release.

### ISSUE THREAD

**Issue by 0x114514BB** [Plachtaa/VITS-fast-fine-tuning#2]
The console outputted:
```
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\MyPath\\inference\\jieba\\dict.txt'
```

It turned out to be fine after I manually add this file from [the repository of Jieba](https://raw.githubusercontent.com/fxsjy/jieba/master/jieba/dict.txt).

To reproduce this error I deleted `dict.txt` and found that Jieba will use cache:

```
DEBUG:jieba:Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\0x114514BB\AppData\Local\Temp\jieba.cache
DEBUG:jieba:Loading model from cache C:\Users\0x114514BB\AppData\Local\Temp\jieba.cache
Loading model cost 0.657 seconds.
DEBUG:jieba:Loading model cost 0.657 seconds.
```

I reproduced this error after deleting `jieba.cache`. Please add `jieba/dict.txt` in the release pack.

**Comment by Plachtaa** [comment]
Thanks for reporting the bug. I have added jieba package and manually set the path to jieba dictionary. It should works fine now.
