### ISSUE TITLE
An error occurred while attempting to run finetune_speaker.py on Windows

### ISSUE THREAD

**Issue by justinjohn0306** [Plachtaa/VITS-fast-fine-tuning#20]
Ideas on how to fix this error?

![Capture](https://user-images.githubusercontent.com/34035011/221299081-38879e12-e953-4de0-85eb-35b3331ad81d.PNG)

**Comment by Plachtaa** [comment]
According to your tqdm display, most probably your character voices are not correctly added to train & val annotations. Also, if you are running locally, it's really difficult to tell which step was wrong exactly.😥

**Comment by justinjohn0306** [comment]
Pretty sure they're annotated correctly

![Capture](https://user-images.githubusercontent.com/34035011/221332226-b85ed433-c2e9-45e2-8275-5ffbe35672a2.PNG)

**Comment by justinjohn0306** [comment]
On colab, this would be step 4, basically, I ran ``python preprocess.py`` and ``python finetune_speaker.py -m "./OUTPUT_MODEL" --max_epochs "30"``

**Comment by justinjohn0306** [comment]
> That's strange. Perhaps do you mind sharing your `.zip` file? I'll try to reproduce your error in colab.

Now, the thing is, it will work for sure on Colab, but on Windows, it's a bit fuzzy.

**Comment by justinjohn0306** [comment]
Here's the ``.zip`` of my character: https://mega.nz/file/skoEjQqS#l0R9zueMZtwx4OY0OIvAVKhlP9poLNV3EO3J13sE0zM

**Comment by Plachtaa** [comment]
My current suggestion is to run `finetune_speaker.py`  under debug mode in your IDE, to check why the dataloader class didn't initialize properly.

**Comment by Plachtaa** [comment]
I have to say this is weird. According to your error message, it seems to be an internal error caused by librosa package.

**Comment by justinjohn0306** [comment]
> 

Yes, it turns out it was librosa all along. I installed librosa 0.9.1 and voila!
![Capture](https://user-images.githubusercontent.com/34035011/221478595-aab63112-e90e-4015-87a9-adb4d6a8d924.PNG)

**Comment by Plachtaa** [comment]
Congratulations!🤗
