### ISSUE TITLE
关于drop_speaker_embed的疑问

### ISSUE THREAD

**Issue by nekomiya-hinata** [Plachtaa/VITS-fast-fine-tuning#204]
如果使用CjangCjengh的vits仓库训练出来的多speaker模型，能够用在这个仓库中进行微调么？
加上`--drop_speaker_embed True`参数后，还能像此仓库的预训练模型一样实现自定义新的speaker么？

**Comment by nekomiya-hinata** [comment]
> 

模型是我自己使用CjangCjengh的vits仓库代码训练出来的，有Discriminator和Generator

**Comment by nekomiya-hinata** [comment]
> 微调需要Discriminator模型，CjangCjengh所分享的都只有Generator，所以不能。而且其中大部分都是纯女声角色，模型对男性声线的泛化能力会很差。

模型是我自己使用CjangCjengh的vits仓库代码训练出来的，有Discriminator和Generator

**Comment by nekomiya-hinata** [comment]
同时训练底模的时候遇到过`RuntimeError: DataLoader worker (pid xxxxxx) is killed by signal: Aborted.`的问题，不知道up有没有呢到过呢？

**Comment by Plachtaa** [comment]
你可以尝试用你的模型进行微调，不过现在只支持`cjke_cleaners2`, `zh_ja_mix_cleaners`已经`chinese_cleaners`这三种，如果你的模型使用的是其它cleaners的话可能需要改一些代码。

**Comment by YuzhouPeng** [comment]
> 同时训练底模的时候遇到过`RuntimeError: DataLoader worker (pid xxxxxx) is killed by signal: Aborted.`的问题，不知道up有没有呢到过呢？

同样遇到这个问题，想问下是怎么解决的呢

**Comment by nekomiya-hinata** [comment]
> > 同时训练底模的时候遇到过`RuntimeError: DataLoader worker (pid xxxxxx) is killed by signal: Aborted.`的问题，不知道up有没有呢到过呢？
> 
> 同样遇到这个问题，想问下是怎么解决的呢

我换成python3.8就好了，不知道是不是版本太高的原因
