### ISSUE TITLE
不添加辅助训练数据是否会导致bug的出现  [疑似BUG]

### ISSUE THREAD

**Issue by jimieguang** [Plachtaa/VITS-fast-fine-tuning#205]
scripts/preprocess_v2.py代码中写到,如果添加辅助训练数据,则会使辅助训练数据+上传数据写入"final_annotation_train.txt",并仅将上传数据写入"final_annotation_val.txt",此时是没问题的

但是如果未添加辅助训练数据,会导致final_annotation_val.txt与final_annotation_train.txt均由上传数据组成,并且在训练的代码中我并未看到有对验证集进行划分的操作(如何有的话请指出,是我眼浊了...),因此训练集与测试集是相同的,此时是否会导致训练出问题

本人使用三千条短语音数据训练后效果不是很好,检查后发现该问题,如果并非bug的话想请教下该如何提高训练效果

**Comment by 40740** [comment]
我训练出来的都是底模的音色？不知道是不是这个原因 测试好几次了。

**Comment by liubin3702** [comment]
是的  会导致验证和训练一样 这个可以自己改一下啊

**Comment by Plachtaa** [comment]
事实上验证集毫无作用，唯一的用处在于evaluate的时候会生成一条语音在tensorboard中作为预览。VITS作为生成式模型，本质上是很难过拟合的

**Comment by 40740** [comment]
> 事实上验证集毫无作用，唯一的用处在于evaluate的时候会生成一条语音在tensorboard中作为预览。VITS作为生成式模型，本质上是很难过拟合的。建议把音频数量减到一百条左右然后勾选ADD_AUXILIARY可以提高效果

老大，请教我的问题，第一次训练我自己的音频用cje可以，但有大佐味，后面用c和cj 训练出来都不是我的音色，都是底模的音色。没改过代码，按照流程来的，请问怎么样解决，测试好几次了都不行。

**Comment by jimieguang** [comment]
> 事实上验证集毫无作用，唯一的用处在于evaluate的时候会生成一条语音在tensorboard中作为预览。VITS作为生成式模型，本质上是很难过拟合的。建议把音频数量减到一百条左右然后勾选ADD_AUXILIARY可以提高效果

感谢回复
