### ISSUE TITLE
步骤4报错

### ISSUE THREAD

**Issue by n3sheltermercury** [Plachtaa/VITS-fast-fine-tuning#21]
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/content/VITS_voice_conversion/finetune_speaker.py", line 133, in run
    train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
  File "/content/VITS_voice_conversion/finetune_speaker.py", line 241, in train_and_evaluate
    evaluate(hps, net_g, eval_loader, writer_eval)
  File "/content/VITS_voice_conversion/finetune_speaker.py", line 279, in evaluate
    y_hat, attn, mask, *_ = generator.module.infer(x, x_lengths, speakers, max_len=1000)
UnboundLocalError: local variable 'x' referenced before assignment
已检查文件目录结构

**Comment by n3sheltermercury** [comment]
final_annotation_val.txt 内是有标注的

**Comment by n3sheltermercury** [comment]
custom charactor voice 内有已处理音频，step 3有正确语音识别结果

**Comment by Plachtaa** [comment]
您好，方便分享一下你的zip文件吗？我会尝试在我这边复现一下错误，如果是bug我会及时修正

**Comment by n3sheltermercury** [comment]
https://1drv.ms/u/s!AhDhRM_LaosOhqc8Z0FslQC_fIW5vg?e=Y70bED
超出了github大小限制 发了OneDrive

**Comment by n3sheltermercury** [comment]
<img width="343" alt="屏幕截图 2023-02-24 203221" src="https://user-images.githubusercontent.com/92708763/221328772-df4b1624-4093-4c81-89d1-27718bb44d53.png">

**Comment by Plachtaa** [comment]
我知道了，因为每条语音都太长导致标注也很长。Dataloader会自动忽略转为音素后长度大于190的句子，所以最后样本相当于是空的，可以尝试切小一点。

**Comment by Plachtaa** [comment]
README里的语音限制已经修改成上限为10秒了，感谢反馈！

**Comment by Plachtaa** [comment]
pipeline现已更新自动切片功能，直接当成长音频上传就不会出现音频过长的问题了，若使用时有bug欢迎反馈。
