### ISSUE TITLE
Step 3 Error

### ISSUE THREAD

**Issue by labx12** [Plachtaa/VITS-fast-fine-tuning#24]
When trying to run step 3 after step 1, I get the following error: 
unzip:  cannot find or open ./custom_character_voice/custom_character_voice.zip, ./custom_character_voice/custom_character_voice.zip.zip or ./custom_character_voice/custom_character_voice.zip.ZIP.
python3: can't open file 'whisper_transcribe.py': [Errno 2] No such file or directory

Not sure what's causing this, as they're both in the file browser.

**Comment by Plachtaa** [comment]
I'm updating the pipeline, so the old notebook is not supported anymore, sorry for the trouble caused.
You can use the [new notebook](https://colab.research.google.com/drive/1pn1xnFfdLK63gVXDwV4zCXfVeo8c-I-0?usp=sharing#scrollTo=4gmpTNtcW2Bt), this has been updated in README.md.

**Comment by Plachtaa** [comment]
By the way, the English documentation of the new notebook is still under construction, it may take several more hours to be fully completed.

**Comment by Plachtaa** [comment]
It is now finished. Sorry for the confusion caused.

**Comment by Plachtaa** [comment]
Please report any bug you met in the new pipeline. onegaishimasu🙏
