### ISSUE TITLE
STEP 5 Error rearrange_speaker

### ISSUE THREAD

**Issue by chiakianyka** [Plachtaa/VITS-fast-fine-tuning#25]
Hi ! I got an error on step 5 for rearrange_speaker
It's appear

rearrange_speaker.py:18: SyntaxWarning: list indices must be integers or slices, not str; perhaps you missed a comma?
  old_emb_g = model_sd(['model']['emb_g.weight'])
Traceback (most recent call last):
  File "rearrange_speaker.py", line 18, in <module>
    old_emb_g = model_sd(['model']['emb_g.weight'])
TypeError: list indices must be integers or slices, not str

**Comment by Plachtaa** [comment]
Thank for reporting, will fix it as soon as possible.

**Comment by Plachtaa** [comment]
It is now be fixed.
