### ISSUE TITLE
太顺利了怎么办

### ISSUE THREAD

**Issue by Kurast703** [Plachtaa/VITS-fast-fine-tuning#265]
之前做过好多个TTS合成，除了极个别（paddlespeech），其它都很麻烦而且失败了，唯独这个一路过于顺利，没有报任何错，一下子有点不太适应（qwq

**Comment by Kurast703** [comment]
为了避免打扰到别人，就把这个其实和项目无关的issue关了哈

**Comment by coreeey** [comment]
合成出来的效果怎么样？
