### ISSUE TITLE
关于大量训练样本进行训练需要注意的一些事项疑问

### ISSUE THREAD

**Issue by TLMEMO** [Plachtaa/VITS-fast-fine-tuning#278]
你好，我正在打算使用这个项目进行大量的数据样本进行训练。比如说上百个角色，大约上万条语音。在训练时是否有需要注意的地方？
比如说学习率、批处理大小?是否需要在训练时再加入辅助训练数据？
另一个问题则是在我拥有足够大的显存的情况下对于超过10秒的短音频是否需要剪裁或分段处理？比如说20秒-30秒那样的。
如果需要，那使用什么工具比较好呢？
期待回答，谢谢！

**Comment by FrankZxShen** [comment]
都不需要。实测使用默认参数不超过10W条语音1张V100即可，100W条语音1张A6000即可；
20秒-30秒音频过长，建议使用2-12秒分段音频。

**Comment by TLMEMO** [comment]
> 都不需要。实测使用默认参数不超过10W条语音1张V100即可，100W条语音1张A6000即可； 20秒-30秒音频过长，建议使用2- 12秒片段音频。

好的，那么请问长音频的存放格式是和短音频一样的吗？也是./raw_audio/下一堆角色名为命名的子文件夹，里面在以 角色名_数字.wav 这样的格式吗？我考虑写一个脚本检测原始音频的长度，然后存放到长音频的文件夹里让这个项目的脚本来处理了，不知道是否可行。
