### ISSUE TITLE
problem at Step3 

### ISSUE THREAD

**Issue by HerocatUED** [Plachtaa/VITS-fast-fine-tuning#283]
ModuleNotFoundError: No module named 'pyopenjtalk'
I can't fix it while I had tried to install with 'python3 -m pip install pyopenjtalk'. Can you help me?

**Comment by HerocatUED** [comment]
Step 3.5 actually

**Comment by HerocatUED** [comment]
![2023-06-14 (2)](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/104823035/66691c7f-835a-4a2f-b370-db2e06372248)

**Comment by Plachtaa** [comment]
Are you running this on a local Linux machine or Windows? Or on Google Colab?

**Comment by HerocatUED** [comment]
Google Colab

**Comment by Plachtaa** [comment]
This is probably because you have kept the session unused for too long, so the session was deleted automatically. Try start a new session and re-run all steps from Step 1.

**Comment by HerocatUED** [comment]
I see, thanks.
