### ISSUE TITLE
合成的声音明显的电音

### ISSUE THREAD

**Issue by zhiyixu** [Plachtaa/VITS-fast-fine-tuning#285]
两个角色， 每个都是15+条音频数据，训练300epoch
合成的声音有很明显的电音，我的数据从电视剧中截取的，然后先用其他软件进行人声分离，在使用这个项目的脚本进行降噪然后一步一步走下去的。
训练结束到最后报错了 见[#284 ](https://github.com/Plachtaa/VITS-fast-fine-tuning/issues/284), 但是尝试直接使用发现能使用，改一下config.json 的文件名就能用了。

电音和这个训练报错有关吗？

**Comment by Plachtaa** [comment]
没有关系，这个只是正常训练结束后结束进程而已，但是在DistributedDataParallel里可能被当成异常了，不用管

**Comment by zhiyixu** [comment]
结果有电音是为什么，是数据量太少还是数据质量的问题

**Comment by Plachtaa** [comment]
我用CJ和CJE底模从来没出现过电音，如果你在用C模型那确实会有可能

**Comment by zhiyixu** [comment]
请问你训练的时候提供的是长语音还是短语言，用了多少条数据？

**Comment by Plachtaa** [comment]
单个角色30条短音频或5分钟长音频

**Comment by zhiyixu** [comment]
麻烦再问下， 30条短语音， 语音的长度在2～10s 左右， 这10s必须全部是语音吗？ 还是讲话断断续续也行

**Comment by Plachtaa** [comment]
最好不要有太多空白
