### ISSUE TITLE
有没有人遇到过卡在训练步骤的问题？

### ISSUE THREAD

**Issue by JoonSumisu** [Plachtaa/VITS-fast-fine-tuning#288]
系统 wsl ubuntu

cuda 12.2
cuda toolkit 12.1

在conda 环境下跑，cmake c++ 安装完成，需求的依赖全部正确安装。
在最后执行步骤 python finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs "100" --drop_speaker_embed True

训练不确定有没有开始，进度条没有动，但是也没有报错。在任务管理器里面，cpu的资源是一直被调动的，但是gpu只有显存被调动。
是否可以理解为是用cpu来跑？是否可以强制指定gpu？

求求大佬们指点下，给点思路。

**Comment by TaoismDeepLake** [comment]
你按下回车看看是不是因为windows命令行的快速编辑模式卡住了

**Comment by JoonSumisu** [comment]
> 你按下回车看看是不是因为windows命令行的快速编辑模式卡住了

应该不是，回车也只是下去走几行，gpu利用率也没有变化

**Comment by JoonSumisu** [comment]
![屏幕截图 2023-06-18 111043](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/77182770/7eb59b18-ec70-4d0f-974a-67c011cd59b8)

现在的情况是这样的，在这个步骤直接冻住。

**Comment by Plachtaa** [comment]
如果你使用cuda 12.2然后按照教程步骤安装了torch的cuda 11.6 or 11.7版本，可能会导致一些问题或者无法使用GPU
请先运行以下脚本:
```
import torch
print(torch.cuda().is_available())
```
以检查GPU是否能够使用

**Comment by JoonSumisu** [comment]
> print(torch.cuda().is_available())

谢谢大佬！！ 果然出错了。cuda这东西搞得我头昏脑涨，我还得想办法从conda环境中管理不同的cuda版本开始研究。非常感谢

**Comment by JoonSumisu** [comment]
更新下
如果使用
torch.cuda.is_available()

回复是 true
现在是出现了在训练到一定程度的时候会 停住

报错为 
/home/racia/anaconda3/envs/vit/lib/python3.8/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/home/racia/anaconda3/envs/vit/lib/python3.8/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
/mnt/e/AI/vit/mel_processing.py:78: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
/mnt/e/AI/vit/mel_processing.py:96: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
/home/racia/anaconda3/envs/vit/lib/python3.8/site-packages/torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.

**Comment by Plachtaa** [comment]
导致训练进度条卡住不动可能的原因非常多，具体可能需要你想办法使用IDE的debug模式去看
或者，如果你在使用WSL Ubuntu，建议直接从docker hub拉取已经安装好正确版本的pytorch和cuda的镜像
或者，重装正确版本的cuda

**Comment by JoonSumisu** [comment]
> docker hub

非常非常感谢！我还是得学会使用docker
