### ISSUE TITLE
有好用的中文底模么？

### ISSUE THREAD

**Issue by qw4654134** [Plachtaa/VITS-fast-fine-tuning#289]
@Plachtaa 大哥，有好用的中文底模了么？目前的C模型效果不太行

**Comment by qw4654134** [comment]
@Plachtaa 看到这里有一个174人的500K step的中文模型，但看起来好像不能用在你的项目里

**Comment by Plachtaa** [comment]
预训练模型需要Discriminator，只发布了Generator的模型是没有办法用来finetune的

**Comment by qw4654134** [comment]
> 预训练模型需要Discriminator，只发布了Generator的模型是没有办法用来finetune的
这里面G和D都有的
https://huggingface.co/jackyqs/vits-aishell3-175-chinese

**Comment by Plachtaa** [comment]
看起来挺不错的，但是作者似乎没有说明使用的g2p工具以及音素词典是哪一个

**Comment by qw4654134** [comment]
> 看起来挺不错的，但是作者似乎没有说明使用的g2p工具以及音素词典是哪一个，config.json按理来说应该存放这些信息，但是没有找到

sad
