### ISSUE TITLE
关于训练模式和底模选择的疑问

### ISSUE THREAD

**Issue by rainyflash** [Plachtaa/VITS-fast-fine-tuning#294]
有几个疑问，求大佬解答：
1.素材长度太短会不会影响训练效果，我目前的素材基本长度都在2-5s。
2.我有八千个素材，是从头训练好还是用预训练好，预训练的话epoch也是越多越好吗？
3.只训练中文模型的话目前是选C还是CJ更好？
4.如果自己找底模是否只需要修改本项目中的sample文件和config文件中sample的部分？
https://github.com/rotten-work/vits-mandarin-windows/tree/mandarin 这个项目中的标贝中文底模怎么样？
5.学习率的大小对训练结果影响大吗？

**Comment by rainyflash** [comment]
还有一个问题是学习率的大小对训练结果影响大吗

**Comment by Plachtaa** [comment]
1. 2~5s 不会；
2. 从预训练开始永远比从头开始快；
3. C
4. 标贝模型的音色泛化能力很差，训出来多是电音；
5. 不要管

**Comment by Plachtaa** [comment]
44100可以，但是这样就得从头开始训练了

**Comment by rainyflash** [comment]
从头开始的意思是底模也要从头开始用44100的音频炼吗

**Comment by Plachtaa** [comment]
对的
