### ISSUE TITLE
可以在原有模型基础上添加角色吗?

### ISSUE THREAD

**Issue by crowcc** [Plachtaa/VITS-fast-fine-tuning#299]
pretrained_models我用了下面的模型
https://huggingface.co/spaces/sayashi/vits-uma-genshin-honkai/resolve/main/model/D_0-p.pth
https://huggingface.co/spaces/sayashi/vits-uma-genshin-honkai/resolve/main/model/G_0-p.pth
https://huggingface.co/spaces/sayashi/vits-uma-genshin-honkai/resolve/main/model/config.json
这个模型里已经有很多角色的声音了吧?但是我训练完之后的config里只有我新加入的角色以及specialweek和zhongli, 可以在原模型角色的基础上加新角色吗?

**Comment by Plachtaa** [comment]
保留原有的音色需要在微调过程中保证每个原角色至少有一两条音频参与训练，否则模型倾向于逐渐遗忘老角色的音色
该仓库的最初版本确实是这么做的，但是为了兼容多个预训练模型，所以统一设定为移除原本的所有音色，将辅助数据设定为固定角色了

**Comment by crowcc** [comment]
了解了, 谢谢
