### ISSUE TITLE
关于训练过程中属性错误

### ISSUE THREAD

**Issue by boypjm998** [Plachtaa/VITS-fast-fine-tuning#30]
作者您好，我在尝试训练的时候出现了如下错误。上面的部分都没有报错，但是如果不勾选的话就会出现bug，同时tensorborad的GUI也没有输出。这里我确认了一下预处理最后的那个文件 `路径|说话人名|因素标注`  的final_anno....train和val.txt文件是有输出的（两个文件是相同的），不知道哪里出了问题。
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/47932982/221453002-eff96ff1-a119-425c-b206-8a095e920d11.png">

**Comment by Plachtaa** [comment]
只有单说话人会报错，就算加上emb_g采样器也会报错，单说话人必须要勾选辅助训练数据或者加入几个dummy speaker来绕过去
