### ISSUE TITLE
关于验证集的划分

### ISSUE THREAD

**Issue by rainyflash** [Plachtaa/VITS-fast-fine-tuning#304]
使用自动标注功能之后发现文件final_annotation_train.txt和final_annotation_val.txt中的内容是完全一致的，他们都包含了全部的数据集标注。那么为了划分验证集是否需要手动删除val.txt中的大部分标注和train.txt中的小部分标注，如果是多个说话者的情况又要怎么划分

**Comment by Plachtaa** [comment]
因为VITS基本不会过拟合，所以验证集都只是做个样子

**Comment by rainyflash** [comment]
好的

**Comment by alannesta** [comment]
> 因为VITS基本不会过拟合，所以验证集都只是做个样子

我也纳闷这个呢, 我没选--add_auxiliary_data 选项, 发现train和val的annotation文件一摸一样~
