### ISSUE TITLE
Python3.8以下本地训练出现SyntaxError

### ISSUE THREAD

**Issue by Pixelboy1018** [Plachtaa/VITS-fast-fine-tuning#308]
由于openai whisper用了海象运算符，是python 3.8以后的特性，您local.md中写的Python>=3.6, <=3.8其实只能用3.8版本
![error](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/52353833/329f5210-024e-40bc-b8ca-846e93a4d378)

**Comment by Plachtaa** [comment]
感谢提醒，已更新LOCAL.md
