### ISSUE TITLE
请问自动去除背景音包括音乐吗？

### ISSUE THREAD

**Issue by Fantendo2001** [Plachtaa/VITS-fast-fine-tuning#31]
请问自动去除背景音包括音乐吗？我自己通过Vocal Remover类似的软件分离音乐和说话声数据会不会效果更好些。

**Comment by Plachtaa** [comment]
用的是Demucs，本身用途就是分离vocal和其它音轨，效果应该是没问题的，不过你自己分离一遍可能更保险吧

**Comment by Fantendo2001** [comment]
感谢！


Best regards,

Yifan ZHAO

**Comment by Fantendo2001** [comment]
![image](https://user-images.githubusercontent.com/59587411/221558199-c611dcf2-836f-43cd-9da5-b16cc6877ba5.png)
在这个位置可以下载去除背景音后的音频，经过对比，比我之前用的这个网站效果好很多：https://vocalremover.org/。
