### ISSUE TITLE
纯中文训练的问题

### ISSUE THREAD

**Issue by gotothehill** [Plachtaa/VITS-fast-fine-tuning#316]
我用纯中文训练后，在web ui界面选择简体中文发音，发音会在语句前后自动包裹上[ZH]，这是什么问题呢？
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/133727960/2b8685a1-cbf8-43f0-bf9b-7045b581a0b7)

**Comment by Plachtaa** [comment]
请选用Mix
