### ISSUE TITLE
你好我是B站北海水母。

### ISSUE THREAD

**Issue by zfzmas** [Plachtaa/VITS-fast-fine-tuning#32]
我想请问能否替换掉那个大佐口音的预训练模型？

**Comment by Plachtaa** [comment]
当然可以，希望你可以提供中文说得更标准的预训练模型，如果你同意的话我会把它加入预训练模型选项之一

**Comment by zfzmas** [comment]
我自己没有啊。用的是400多M的那个G_0和D_0。替换之后训练时候就出错了。标贝的那个G95300什么的来着只有G，没有D。D又是什么？
