### ISSUE TITLE
训练时报错

### ISSUE THREAD

**Issue by Crassco** [Plachtaa/VITS-fast-fine-tuning#321]
如图
![8QG8MP39YY D{02SF3$XOL](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/138987882/10753fc6-682a-404e-be75-03d52f22b668)

**Comment by Plachtaa** [comment]
colab更新了pydantic的包，现已修改colab以控制pydantic的版本

**Comment by mbx213** [comment]
现在部署环境那块选y/n，但是选了y后面也还是不行，作者你自己试试后面训练那块，应该是更新之后还有地方得改，不然成功不了了

**Comment by Plachtaa** [comment]
稍微修改了pydantic的处理方式，现在不会卡住了
