### ISSUE TITLE
在本地尝试继续训练时出现报错导致启动训练失败

### ISSUE THREAD

**Issue by ling0403** [Plachtaa/VITS-fast-fine-tuning#323]
之前初次训练过程中由于torch版本太高（2.1.0dev）出现过warning但并未失败，怀疑继续训练失败可能是torch版本过高，但是退版本至说明中的1.13.1+cu117后，依旧报错依旧如下，继续训练时并未更改过G_0.pth，D_0.pth与finetune_speaker.json(依旧是huggingface上的预训练模型)。望解决，感谢。

(venv) G:\VITS-fast-fine-tuning>python finetune_speaker_v2.py -m ./OUTPUT_MODEL --max_epochs "40" --drop_speaker_embed False --cont True
--- Logging error ---
Traceback (most recent call last):
  File "D:\py\py38\lib\logging\__init__.py", line 1088, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe6' in position 1322: illegal multibyte sequence
Call stack:
  File "<string>", line 1, in <module>
  File "D:\py\py38\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\py\py38\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "D:\py\py38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "D:\py\py38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "D:\py\py38\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "G:\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 63, in run
    logger.info(hps)
Message: {'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['cjke_cleaners2'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 1, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'N', 'Q', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ɑ', 'æ', 'ʃ', 'ʑ', 'ç', 'ɯ', 'ɪ', 'ɔ', 'ɛ', 'ɹ', 'ð', 'ə', 'ɫ', 'ɥ', 'ɸ', 'ʊ', 'ɾ', 'ʒ', 'θ', 'β', 'ŋ', 'ɦ', '⁼', 'ʰ', '`', '^', '#', '*', '=', 'ˈ', 'ˌ', '→', '↓', '↑', ' '], 'speakers': {'skadi': 0}, 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 40, 'cont': True, 'drop_speaker_embed': False, 'train_with_pretrained_model': True, 'preserved': 4}
Arguments: ()
INFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['cjke_cleaners2'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 1, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', ',', '.', '!', '?', '-', '~', '…', 'N', 'Q', 'a', 'b', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'ɑ', 'æ', 'ʃ', 'ʑ', 'ç', 'ɯ', 'ɪ', 'ɔ', 'ɛ', 'ɹ', 'ð', 'ə', 'ɫ', 'ɥ', 'ɸ', 'ʊ', 'ɾ', 'ʒ', 'θ', 'β', 'ŋ', 'ɦ', '⁼', 'ʰ', '`', '^', '#', '*', '=', 'ˈ', 'ˌ', '→', '↓', '↑', ' '], 'speakers': {'skadi': 0}, 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 40, 'cont': True, 'drop_speaker_embed': False, 'train_with_pretrained_model': True, 'preserved': 4}
INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
latest_checkpoint_path:././OUTPUT_MODEL\G_latest.pth
INFO:OUTPUT_MODEL:Loaded checkpoint '././OUTPUT_MODEL\G_latest.pth' (iteration 151)
latest_checkpoint_path:././OUTPUT_MODEL\D_latest.pth
INFO:OUTPUT_MODEL:Loaded checkpoint '././OUTPUT_MODEL\D_latest.pth' (iteration 151)
  0%|                                                                                           | 0/12 [00:00<?, ?it/s]G:\VITS-fast-fine-tuning\mel_processing.py:78: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
G:\VITS-fast-fine-tuning\mel_processing.py:96: FutureWarning: Pass sr=22050, n_fft=1024, n_mels=80, fmin=0.0, fmax=None as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel = librosa_mel_fn(sampling_rate, n_fft, num_mels, fmin, fmax)
INFO:torch.nn.parallel.distributed:Reducer buckets have been rebuilt in this iteration.
D:\py\py38\venv\lib\site-packages\torch\autograd\__init__.py:197: UserWarning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
grad.sizes() = [1, 9, 96], strides() = [31200, 96, 1]
bucket_view.sizes() = [1, 9, 96], strides() = [864, 96, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\distributed\c10d\reducer.cpp:339.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
INFO:OUTPUT_MODEL:Train Epoch: 151 [0%]
INFO:OUTPUT_MODEL:[2.390634536743164, 2.323054552078247, 8.114237785339355, 18.55348777770996, 1.3119269609451294, 1.5069361925125122, 1800, 0.0002]
DEBUG:matplotlib:matplotlib data path: D:\py\py38\venv\lib\site-packages\matplotlib\mpl-data
DEBUG:matplotlib:CONFIGDIR=C:\Users\24779\.matplotlib
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 151 to ././OUTPUT_MODEL\G_latest.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 151 to ././OUTPUT_MODEL\D_latest.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 151 to ././OUTPUT_MODEL\G_1800.pth
INFO:OUTPUT_MODEL:Saving model and optimizer state at iteration 151 to ././OUTPUT_MODEL\D_1800.pth
Maximum epoch reached, closing training...
  0%|                                                                                           | 0/12 [00:19<?, ?it/s]
None
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 351, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "D:\py\py38\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "D:\py\py38\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 198, in start_processes
    while not context.join():
  File "D:\py\py38\venv\lib\site-packages\torch\multiprocessing\spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

**Comment by Plachtaa** [comment]
将`max_epochs`改为10000可以解决

**Comment by ling0403** [comment]
已解决，感谢

**Comment by Pnameabc** [comment]
> 已解决，感谢

请问下，怎么解决的呀，我也是遇到这个问题，max_epochs设置100了，还是一样的报这个错 导致启动训练失败
