### ISSUE TITLE
有办法添加一个功能就是训练过程中每隔几步的训练会自动储存模型文件pth和json文件道谷歌云盘吗？比如设定间隔训练100次自动储存一次当下的模型。后面再储存的会覆盖之前的模型。这样的功能。

### ISSUE THREAD

**Issue by Lemondogdog** [Plachtaa/VITS-fast-fine-tuning#330]
有办法添加一个功能就是训练过程中每隔几步的训练会自动储存模型文件pth和json文件道谷歌云盘吗？比如设定间隔训练100次自动储存一次当下的模型。后面再储存的会覆盖之前的模型。这样的功能。

**Comment by Plachtaa** [comment]
加了

**Comment by Lemondogdog** [comment]
> 加了

还好有自动保存的，现在它gpu每天的限定量使用来计算，我现在获得了有G_latest.pth等这些自动保存的信息后。我下次接着训练模型的话要如何设置呢？

比如我这版有最后一次是计算到G_5500.pth的模型，还能再下次训练中从这G_5500.pth开始继续往后训练计算吗？

还有一个问题是我们每次想要接着上一次的模型继续追加训练的话。那个段音频上传和Whisper处理语音识别文字的标注还抖音再走一遍吗？这个语音识别文本的标注也挺长时间的，有办法上传之前标注过的文档上传使用，不用再重新等待它Whisper再识别标注一次吗？
