### ISSUE TITLE
本地训练如何调整batch_size和关闭fp16训练？

### ISSUE THREAD

**Issue by blueleigong** [Plachtaa/VITS-fast-fine-tuning#334]
如题，发现batch_size太低没有充分利用本地显卡资源

**Comment by Plachtaa** [comment]
请自行修改后缀为`.json`的config文件

**Comment by blueleigong** [comment]
请问具体是修改哪个目录下的config文件呢？修改output文件夹下的发现会被复写。

**Comment by blueleigong** [comment]
已解决，通过修改config目录下的modified_finetune_speaker.json调整
