### ISSUE TITLE
求助关于windows环境下本地部署需要哪些注意事项呢

### ISSUE THREAD

**Issue by robinfelix4** [Plachtaa/VITS-fast-fine-tuning#34]
首先感谢大佬的分享和优化！我自己在尝试本地windows 环境下CONDA python3.9部署后，安装环境未出现错误，于是尝试下一步
Q1，两个预训练模型都下载了（CJ与CJE），如果想更换其他标准汉语单语种（嗯……现在大佐味道很浓），这个是不是就是关键的部分？（当然还有configs/finetune_speaker.json的配置文件）
Q2，sampled_audio4ft这个文件以及.TXT是用来做什么的呢，（应该是数据集验证吧，看到里面有音素的标注，但是800多条，缺失了很大一部分中文的标注）自己更换的话，是否需要同步进行替换？或者如何进行音素的转换？
Q3，在本地命令行输入“python denoise_audio.py”去噪，“python short_audio_transcribe.py --languages "CJE" --whisper_size medium”后，发现并未识别出中文字幕，只是一直一行一行显示“Detected language: zh”直到结束。
Q4，由于失败未进行下一步。若使用辅助训练，则是否命令行输入“python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs "20"”
期待大佬您的答疑解惑！

**Comment by Plachtaa** [comment]
Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模；
Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果
Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了
Q4: 没生成标注是没法训练的

**Comment by robinfelix4** [comment]
感谢大佬！ORZ，持续向您学习！

> Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的

感谢大佬！ORZ，持续向您学习！

**Comment by robinfelix4** [comment]
> Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的



> Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的

您好大佬，Q3已解决，原因是conda环境没正确安装PYTORCH gpu版本。
Q4已经成功生成标注
现在到了训练步骤，STEP4，想问下您如何在本地命令行输入命令开始训练呢？
python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs="30"开始报错（应该是我传参格式有误）

**Comment by Plachtaa** [comment]
> > Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的
> 
> > Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的
> 
> 您好大佬，Q3已解决，原因是conda环境没正确安装PYTORCH gpu版本。 Q4已经成功生成标注 现在到了训练步骤，STEP4，想问下您如何在本地命令行输入命令开始训练呢？ python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs="30"开始报错（应该是我传参格式有误）

命令行不用加引号

**Comment by robinfelix4** [comment]
> > > Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的
> > 
> > 
> > > Q1: 大佐味浓是因为VITS本身不是什么大模型，多语言混训是会降低在单语言上的性能的，目前正在寻找高质量中文底模； Q2: 这个是从预训练那个十几万条的数据集抽样出来做辅助的，防止被whisper的某些错误标注带偏，然后经实验发现用这种方式训练样本很小的新说话人也能有比较好的效果 Q3: 你没开GPU的话whisper就会出现这种情况，以前有人在colab里出现过同样的错误，开了GPU就好了 Q4: 没生成标注是没法训练的
> > 
> > 
> > 您好大佬，Q3已解决，原因是conda环境没正确安装PYTORCH gpu版本。 Q4已经成功生成标注 现在到了训练步骤，STEP4，想问下您如何在本地命令行输入命令开始训练呢？ python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs="30"开始报错（应该是我传参格式有误）
> 
> 命令行不用加引号
大佬您在帮忙看下，麻烦啦
python finetune_speaker_v2.py -m "./OUTPUT_MODEL" --max_epochs=30
--- Logging error ---
Traceback (most recent call last):
  File "J:\ANACONDA\envs\fast\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
UnicodeEncodeError: 'gbk' codec can't encode character '\xe6' in position 1327: illegal multibyte sequence
Call stack:
  File "<string>", line 1, in <module>
  File "J:\ANACONDA\envs\fast\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "J:\ANACONDA\envs\fast\lib\multiprocessing\spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "J:\ANACONDA\envs\fast\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "J:\ANACONDA\envs\fast\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "J:\ANACONDA\envs\fast\lib\site-packages\torch\multiprocessing\spawn.py", line 69, in _wrap
    fn(i, *args)
  File "J:\ANACONDA\envs\fast\VITS-fast-fine-tuning\finetune_speaker_v2.py", line 63, in run
    logger.info(hps)

**Comment by Plachtaa** [comment]
说了不要加引号😅
另外如果你非要在本地，甚至还是windows上训练的话我建议你自己多研究研究，我也没什么时间一直给你回答这种低级错误是什么导致的，拜托了
