### ISSUE TITLE
如何将vits 的模型转化成 onnx？

### ISSUE THREAD

**Issue by ocheng2005** [Plachtaa/VITS-fast-fine-tuning#344]
在调用 torch.onnx.export ，经常遇到如下问题：TypeError: SynthesizerTrn.forward() missing 2 required positional arguments: 'y' and 'y_lengths'。

**Comment by ocheng2005** [comment]
VITS-Umamusume-voice-synthesizer 已解决了。

**Comment by liuxuanfeng3364** [comment]
> VITS-Umamusume-voice-synthesizer 已解决了。

请问是怎么解决的呢，可以提供一下代码么

**Comment by ocheng2005** [comment]
> > VITS-Umamusume-voice-synthesizer 已解决了。
> 
> 请问是怎么解决的呢，可以提供一下代码么

https://huggingface.co/spaces/Plachta/VITS-Umamusume-voice-synthesizer

**Comment by csukuangfj** [comment]
https://github.com/csukuangfj/vits_chinese

可以看下上面的导出代码。

导出后，可以直接用
https://github.com/k2-fsa/sherpa-onnx
去部署。它是 c++ 实现的，提供各种语言的 api, 比如 c/python/go/kotlin/swift/c# 等，支持 ios/android/windows/linux/macos.

https://k2-fsa.github.io/sherpa/onnx/tts/apk.html
这里有编译好的 android apk 供你下载。

https://huggingface.co/spaces/k2-fsa/text-to-speech
有转换好的模型供你在线体验。
