### ISSUE TITLE
能否支持挂载谷歌硬盘？

### ISSUE THREAD

**Issue by vic233333** [Plachtaa/VITS-fast-fine-tuning#35]
COLAB自带的上传和下载功能非常不好用，限速非常严重，而且会因为意外的断连导致数据全部丢失。可以添加几行简单的代码就集成这个功能，请问能不能集成到那个Jupiter里面呢？
举个例子，[so-vits-svc](https://github.com/innnky/so-vits-svc)的[Jupiter](https://colab.research.google.com/drive/1_-gh9i-wCPNlRZw6pYF-9UufetcVrGBX?usp=sharing)就实现了这个功能。

**Comment by Plachtaa** [comment]
啊，我昨天更新的新笔记本就支持了，你可以看一下

**Comment by Plachtaa** [comment]
顺带一提老的已经不能用了

**Comment by vic233333** [comment]
> 感谢建议，你说的这个问题确实很严重，我昨天更新的新笔记本就支持挂Google云端硬盘了，你可以看一下README里的新链接。 顺带一提老的已经不能用了

非常感谢！❤
