### ISSUE TITLE
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

### ISSUE THREAD

**Issue by WellTung666** [Plachtaa/VITS-fast-fine-tuning#353]
训练Epoch结束后出现错误：
```
INFO:OUTPUT_MODEL_test:Train Epoch: 11 [0%]
INFO:OUTPUT_MODEL_test:[2.5180983543395996, 2.176342248916626, 6.351111888885498, 20.8907527923584, 1.3190431594848633, 2.5211775302886963, 110, 0.00019975014057813518]
Maximum epoch reached, closing training...
  0%|                                                                                                                                                                               | 0/11 [00:04<?, ?it/s]
None
Traceback (most recent call last):
  File "finetune_speaker_v2.py", line 372, in <module>
    main()
  File "finetune_speaker_v2.py", line 55, in main
    mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
  File "/home/ft/.conda/envs/VIST/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ft/.conda/envs/VIST/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ft/.conda/envs/VIST/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in join
    raise ProcessExitedException(
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1
```

尝试运行推理：`python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True`报错：
```
Traceback (most recent call last):
  File "VC_inference.py", line 93, in <module>
    hps = utils.get_hparams_from_file(args.config_dir)
  File "/home/ft/Project/VITS-fast-fine-tuning/utils.py", line 362, in get_hparams_from_file
    with open(config_path, "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: './finetune_speaker.json'
```
请问这是什么问题呢？谢谢～

**Comment by Andision** [comment]
教程有点小问题，配置文件在configs里，你可以手动加运行参数或者改源代码里config的位置
试试这个命令

`python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True --config_dir ./configs/modified_finetune_speaker.json `

**Comment by WellTung666** [comment]
> 教程有点小问题，配置文件在configs里，你可以手动加运行参数或者改源代码里config的位置 试试这个命令
> 
> `python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True --config_dir ./configs/modified_finetune_speaker.json `

所以第一个错误`torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1` 是不会影响模型的训练结果的吗？modified_finetune_speaker.json 是固定的还是训练模型的时候生成的呢？ 非常感谢～

**Comment by WellTung666** [comment]
> > > 教程有点小问题，配置文件在configs里，你可以手动加运行参数或者改源代码里config的位置 试试这个命令
> > > `python VC_inference.py --model_dir ./OUTPUT_MODEL/G_latest.pth --share True --config_dir ./configs/modified_finetune_speaker.json `
> > 
> > 
> > 所以第一个错误`torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1` 是不会影响模型的训练结果的吗？modified_finetune_speaker.json 是固定的还是训练模型的时候生成的呢？ 非常感谢～
> 
> > 所以第一个错误torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1 是不会影响模型的训练结果的吗？
> 
> 根据 #284 中作者的回复，应该是正常的
> 
> > modified_finetune_speaker.json 是固定的还是训练模型的时候生成的呢？
> 
> 我也是用这个模型但不是作者哈哈，我理解是在`preprocess_v2.py`里生成的
> 
> ```python
> with open("./configs/modified_finetune_speaker.json", 'w', encoding='utf-8') as f:
>             json.dump(hps, f, indent=2)
> ```
这个回复我也看到了，但是不太确定是不是对的哈哈哈哈
我还以为modified_finetune_speaker.json是仓库自带的，刚才对比了一下确实有不一样的地方，我再重新训练试一试，非常感谢你的回答！！！

**Comment by Andision** [comment]
😊
