### ISSUE TITLE
连colab的代码都很容易出错

### ISSUE THREAD

**Issue by Katana-O** [Plachtaa/VITS-fast-fine-tuning#358]
首先很感谢作者的开源，但是激进的更新实在让代码很难部署起来，连试起来我都做不到，能不能出个稳定版。

**Comment by Plachtaa** [comment]
不是我在更新，是colab的虚拟机环境一直在更新导致如果colab的代码不一直改就没法用

**Comment by 2579356425** [comment]
> 首先很感谢作者的开源，但是激进的更新实在让代码很难部署起来，连试起来我都做不到，能不能出个稳定版。

可以参考#351 ，HWcomss给出了可以运行的colab链接

**Comment by Plachtaa** [comment]
> > 首先很感谢作者的开源，但是激进的更新实在让代码很难部署起来，连试起来我都做不到，能不能出个稳定版。
> 
> 可以参考#351 ，HWcomss给出了可以运行的colab链接

已经参考[HWcomss](https://github.com/HWcomss)的notebook进行了修正，现在可以正常运行了
