### ISSUE TITLE
关于webui-inference本地运行和推理的一个小问题

### ISSUE THREAD

**Issue by qingshanze** [Plachtaa/VITS-fast-fine-tuning#360]
可选项有4个，选中文开头结尾都会自动添加[ZH],只有Mix不会，请问有什么办法能修改使得其他选项和Mix一样，不会额外添加类似的识别语吗？

**Comment by anfogy** [comment]
如果不加那模型就无法识别出对应的语言

**Comment by qingshanze** [comment]
> 如果不加那模型就无法识别出对应的语言

谢谢回复！我试了在webui界面，可以选择识别的语言，但是输出音频的开头和结尾还是添加了zh,en这种识别语，想知道有没有办法去掉，用Mix类型音调变来变去的o o

**Comment by anfogy** [comment]
我去测试了一下，请注意您要生成的语句中不含有换行符号，不然会转不了国际音标

**Comment by qingshanze** [comment]
> 我去测试了一下，请注意您要生成的语句中不含有换行符号，不然会转不了国际音标

您好，请问您有用webui-inference进行测试效果吗，是否有同样的情况发送呢？

**Comment by qingshanze** [comment]
> 我去测试了一下，请注意您要生成的语句中不含有换行符号，不然会转不了国际音标

您好，请问您有用webui-inference进行测试效果吗，是否有同样的情况发送呢？

**Comment by anfogy** [comment]
> > 我去测试了一下，请注意您要生成的语句中不含有换行符号，不然会转不了国际音标
> 
> 您好，请问您有用webui-inference进行测试效果吗，是否有同样的情况发送呢？

是的，cmd和webui都试了
