### ISSUE TITLE
能否加一个cleaners，或者自己自定义一个

### ISSUE THREAD

**Issue by kirbystudy** [Plachtaa/VITS-fast-fine-tuning#364]
因为我选的纯中文的模型，cleaner处理的时候转日文注音，我想用纯拼音的方式，请问可以添加一个cleaner吗。谢谢！

**Comment by Plachtaa** [comment]
这是中文的注音符号，早在拼音出现之前就有了，不是日文

**Comment by Plachtaa** [comment]
https://zh.wikipedia.org/zh-sg/%E6%B3%A8%E9%9F%B3%E7%AC%A6%E8%99%9F

**Comment by kirbystudy** [comment]
好的谢谢，我纠正一下这个是汉语的标音，那我能不能用上面chinese_cleaners1这种拼音的方式进行训练呢

**Comment by Plachtaa** [comment]
可以，但是你需要从零开始训练

**Comment by kirbystudy** [comment]
好吧，看来是预模型不支持chinese_cleaners1这种方式。谢谢。
