### ISSUE TITLE
推理出现size mismatch for enc_p.emb.weight错误

### ISSUE THREAD

**Issue by WellTung666** [Plachtaa/VITS-fast-fine-tuning#369]
运行 VC_inference.py后出现错误：
```
Traceback (most recent call last):
  File "VC_inference.py", line 104, in <module>
    _ = utils.load_checkpoint(args.model_dir, net_g, None)
  File "/home/ft/Project/VITS-fast-fine-tuning/utils.py", line 177, in load_checkpoint
    model.load_state_dict(new_state_dict)
  File "/home/ft/.conda/envs/VIST/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SynthesizerTrn:
	size mismatch for enc_p.emb.weight: copying a param with shape torch.Size([52, 192]) from checkpoint, the shape in current model is torch.Size([50, 192]).
```
同样的错误出现在训练好的模型（本地可以成功inference）放在其他项目却报错，请问这是什么问题呢？和什么有关系呢？谢谢～
_https://github.com/zixiiu/Digital_Life_Server/issues/78_

**Comment by anfogy** [comment]
有可能是load checkpoint的问题，其他项目和你的模型不匹配？看不懂你想表达什么

**Comment by WellTung666** [comment]
> 有可能是load checkpoint的问题，其他项目和你的模型不匹配？看不懂你想表达什么

已解决～

**Comment by RestlessDB** [comment]
您好，我也遇到了同样的问题，能说一下你是怎么解决的吗

**Comment by anfogy** [comment]
> 您好，我也遇到了同样的问题，能说一下你是怎么解决的吗

重新配置

**Comment by WellTung666** [comment]
> 您好，我也遇到了同样的问题，能说一下你是怎么解决的吗

检查symbols是否一致。

**Comment by RestlessDB** [comment]
我预训练模型选的C纯中文，训练好的finetune_speaker中的symbols与Digital Life里paimon6k的symbols一模一样，都是50个。

**Comment by zicheqingluo** [comment]
C没问题，CJE报这个错

**Comment by potatoker** [comment]
> > 您好，我也遇到了同样的问题，能说一下你是怎么解决的吗
> 
> 检查symbols是否一致。

确实digitalLife那个给到的config file 里面symols是 50 个，但是加载模型的时候维度是 52，请问那config file是没法修改来适配这个已有的模型了吗？这里您说的解决是指重新训练吗

**Comment by WellTung666** [comment]
> > > 您好，我也遇到了同样的问题，能说一下你是怎么解决的吗
> > 
> > 
> > 检查symbols是否一致。
> 
> 确实digitalLife那个给到的config file 里面symols是 50 个，但是加载模型的时候维度是 52，请问那config file是没法修改来适配这个已有的模型了吗？这里您说的解决是指重新训练吗

config file是训练模型开始的时候就要给好的和模型是对应匹配使用的，可以尝试重新训练自己的模型。
