### ISSUE TITLE
Pretraining details

### ISSUE THREAD

**Issue by nmfisher** [Plachtaa/VITS-fast-fine-tuning#37]
Great work! Was hoping you could give some brief details on your pretraining - mostly how many hours of data per speaker and how many epochs.

**Comment by Plachtaa** [comment]
Hi, thank you for your interest!
The trilingual model is trained on a dataset of around 120k voice-text pairs, where each audio is around 2~15 seconds, for 420 epochs. 
The other Chinese & Japanese model is not trained by me so I'm not sure about dataset details, but it was trained for more than 600 epochs.

**Comment by nmfisher** [comment]
Thank you!
