### ISSUE TITLE
本地local搭建第12步, python VC_inference.py 错误

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [Plachtaa/VITS-fast-fine-tuning#372]
按照给出的教程，出现模块缺失错误，无法构建环境，现在应该怎么处理

**Comment by anfogy** [comment]
在没有错误报告的情况下诊断错误无疑是帮你算命，模块缺失是怎么样的缺失，无法构建环境又是怎样无法构建，截图呢？log呢？你在报错前执行了什么？开发者们不是算命大师

**Comment by anfogy** [comment]
根据Google Colab Step 4的代码，执行`VC_inference.py`前需要先执行`cp ./configs/modified_finetune_speaker.json ./finetune_speaker.json`
