### ISSUE TITLE
处理音频数据过程中，自动停止

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [Plachtaa/VITS-fast-fine-tuning#376]
再处理数据的时候，自动停止了
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/87591236/590ca65d-d1ba-4317-aac7-6898a0c86ce5)

**Comment by anfogy** [comment]
自动停止... 处理完了就自动停止啊，你那个报错是因为你没有下辅助数据集，请cd到VITS-fast-fine-tuning并运行
```bash
wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip
unzip sampled_audio4ft_v2.zip
```

**Comment by anfogy** [comment]
> > 自动停止... 处理完了就自动停止啊，你那个报错是因为你没有下辅助数据集，请cd到VITS-fast-fine-tuning并运行
> > ```shell
> > wget https://huggingface.co/datasets/Plachta/sampled_audio4ft/resolve/main/sampled_audio4ft_v2.zip
> > unzip sampled_audio4ft_v2.zip
> > ```
> 
> 谢谢解决了，我还有个问题。如果我把一部分训练的音频放入sampled中，会增加训练出来模型音色准确吗，还是这个sampled文件夹中的音频是固定不变的，大佬有空回个信

不会，里面的音频是固定不变的，就是所谓的“辅助数据集”，放进去就和放到custom_character是一样的
