### ISSUE TITLE
drop_speaker_embed

### ISSUE THREAD

**Issue by ltm920716** [Plachtaa/VITS-fast-fine-tuning#378]
hello everyone，
there is a param：drop_speaker_embed，but I do not find where it is used in the source code，anyone could help answering me？Thanks！

**Comment by anfogy** [comment]
`drop_speaker_embed` should means it will automatically create a config.json, but unfortunately I can't find it in `finetune_speaker_v2.py` either... So let's just pretend it does nothing but still keep it there(since it's working lol), not a big deal.

**Comment by yiwei0730** [comment]
Yes, maybe in the last version the drop_speaker_embed  used in when you finetune on a new speaker you should drop the pretrained speaker embedding，but in the new version，it just use hps.speaker to easy create the new model and load it in key value, so the drop_speaker_embed just ignore it
