### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by sixTiger** [Plachtaa/VITS-fast-fine-tuning#380]
行长（hangzhang）会读成（xingchang），请问怎么可以优化一下类似的问题

**Comment by anfogy** [comment]
我如果没记错是用pypinyin转拼音的，处理这个问题你可能要单独用pypinyin尝试一下然后再看看哪里能改掉，pypi上应该没有可以替换的库了

**Comment by sixTiger** [comment]
https://github.com/mozillazg/python-pinyin#id5

测试了一下  cc_cedict  可以解决一部分多音字读错的问题

**Comment by sixTiger** [comment]
问题已经解决了

**Comment by WellTung666** [comment]
> https://github.com/mozillazg/python-pinyin#id5
> 
> 测试了一下 cc_cedict 可以解决一部分多音字读错的问题

你好，请问这个要怎么使用呢？

**Comment by sixTiger** [comment]
修改 mandarin.py
chinese_to_bopomofo
<img width="515" alt="image" src="https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/10770733/d046bf93-8083-49dc-a6e2-2da2b943a1fe">

**Comment by shirubei** [comment]
from pypinyin import lazy_pinyin, BOPOMOFO, load_phrases_dict

然后在下面这个函数里加load_phrases_dict这样一行，具体如下

def chinese_to_bopomofo(text):
    load_phrases_dict({'行长': [['háng'], ['zhǎng']]})
