### ISSUE TITLE
如何控制停顿？

### ISSUE THREAD

**Issue by v-yunbin** [Plachtaa/VITS-fast-fine-tuning#391]
使用CJE预训练模型，合成的音频里没有任何停顿，和训练数据有关系吗
合成示例：大家好，尊敬的评委、亲爱的观众们。今天，我站在这里，心中充满着激情和澎湃！

**Comment by anfogy** [comment]
你训练了多少步？多少条训练数据？

**Comment by v-yunbin** [comment]
> 你训练了多少步？多少条训练数据？

3309条，1600个epoch，

**Comment by anfogy** [comment]
那不应该啊，我2000条，40epoch都有很好的效果了，尝试多加几个标点试试

**Comment by v-yunbin** [comment]
> 那不应该啊，我2000条，40epoch都有很好的效果了，尝试多加几个标点试试

我在现在的这个recipe上做了一些改动：训练的时候加了一个emotion embedding

**Comment by anfogy** [comment]
可是原本的inference已经有一定的语气(emotion)了吧，还有必要加emotion embedding吗？会不会是与原本的冲突？

**Comment by anfogy** [comment]
能否把已改动的项目放到github repo里？

**Comment by v-yunbin** [comment]
> 可是原本的inference已经有一定的语气(emotion)了吧，还有必要加emotion embedding吗？会不会是与原本的冲突？

感觉挺有必要，可以改变说话的语气（开心、伤心、惊讶等）

**Comment by v-yunbin** [comment]
> 能否把已改动的项目放到您的forked github repo里？

公司不允许往github push
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/38179632/a5663323-1781-4c8a-8791-a84db746d7c1)

**Comment by anfogy** [comment]
> > 可是原本的inference已经有一定的语气(emotion)了吧，还有必要加emotion embedding吗？会不会是与原本的冲突？
> 
> 感觉挺有必要，可以改变说话的语气（开心、伤心、惊讶等）

您是参考[Emotional VITS](https://github.com/innnky/emotional-vits)来修改代码的吗？

**Comment by v-yunbin** [comment]
> > > 可是原本的inference已经有一定的语气(emotion)了吧，还有必要加emotion embedding吗？会不会是与原本的冲突？
> > 
> > 
> > 感觉挺有必要，可以改变说话的语气（开心、伤心、惊讶等）
> 
> 您是参考[Emotional VITS](https://github.com/innnky/emotional-vits)来修改代码的吗？

是的，但他的那个有问题，能跑通但合成音频为空。

**Comment by anfogy** [comment]
如果无法提供代码的话我也无法诊断错误，因为我无法确保我自己改的版本会与您的一模一样，所以很抱歉，你可以尝试在[Emotional VITS](https://github.com/innnky/emotional-vits)那边提issue

**Comment by v-yunbin** [comment]
> 如果无法提供代码的话我也无法诊断错误，因为我无法确保我自己改的版本会与您的一模一样，所以很抱歉，你可以尝试在[Emotional VITS](https://github.com/innnky/emotional-vits)那边提issue

行吧，我提了问题没人回，我在咱们这个recipe上改了一版，至少可以用，就是停顿有点问题。

**Comment by anfogy** [comment]
> > 如果无法提供代码的话我也无法诊断错误，因为我无法确保我自己改的版本会与您的一模一样，所以很抱歉，你可以尝试在[Emotional VITS](https://github.com/innnky/emotional-vits)那边提issue
> 
> 行吧，我提了问题没人回，我在咱们这个recipe上改了一版，至少可以用，就是停顿有点问题。

能发下wav文件吗，后缀改txt，我这边改回来就行。试过加多点标点吗？

**Comment by v-yunbin** [comment]
> > > 如果无法提供代码的话我也无法诊断错误，因为我无法确保我自己改的版本会与您的一模一样，所以很抱歉，你可以尝试在[Emotional VITS](https://github.com/innnky/emotional-vits)那边提issue
> > 
> > 
> > 行吧，我提了问题没人回，我在咱们这个recipe上改了一版，至少可以用，就是停顿有点问题。
> 
> 能发下wav文件吗，后缀改txt，我这边改回来就行。试过加多点标点吗？

感谢啦 我自解决了，把emotion wav的静音段调大之后，合成就正常了
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/38179632/55474b35-7072-413b-a175-93b63ba61da9)

**Comment by anfogy** [comment]
那没事了，close吧，感谢您对项目作出的贡献
