### ISSUE TITLE
合成音频的语调问题

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [Plachtaa/VITS-fast-fine-tuning#392]
在我合成的音频中，会有几个字的音调很奇怪，我使用的是中文C语音模型进行的合成，音频中会有几个字发音不准，这个问题如何解决

**Comment by anfogy** [comment]
增加数据量或加入辅助数据集

**Comment by anfogy** [comment]
> ![image](https://user-images.githubusercontent.com/87591236/260660767-36b9191a-cfbc-4ebc-8242-36fcf1cdebcc.png)
> 是这个辅助数据吗，然后我能不能修改，来自定义

是的，您可以修改，当然不推荐修改，例如移除所有男生女生之类的，如果是想加入其他东西不如直接放在训练数据里
