### ISSUE TITLE
Colab finetune error

### ISSUE THREAD

**Issue by sashasubbbb** [Plachtaa/VITS-fast-fine-tuning#4]
I've loaded the dataset into colab but got this error on step 4:

> 0% 0/55 [00:37<?, ?it/s]
> Traceback (most recent call last):
>   File "finetune_speaker.py", line 320, in <module>
>     main()
>   File "finetune_speaker.py", line 55, in main
>     mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/content/VITS_voice_conversion/finetune_speaker.py", line 133, in run
>     train_and_evaluate(rank, epoch, hps, [net_g, net_d], [optim_g, optim_d], [scheduler_g, scheduler_d], scaler, [train_loader, eval_loader], logger, [writer, writer_eval])
>   File "/content/VITS_voice_conversion/finetune_speaker.py", line 241, in train_and_evaluate
>     evaluate(hps, net_g, eval_loader, writer_eval)
>   File "/content/VITS_voice_conversion/finetune_speaker.py", line 279, in evaluate
>     y_hat, attn, mask, *_ = generator.module.infer(x, x_lengths, speakers, max_len=1000)
> UnboundLocalError: local variable 'x' referenced before assignment

My dataset is 10 voices which include 10-30 10 second .mp3s.

**Comment by Plachtaa** [comment]
This is most probably the program didn't recognize your uploaded voices properly, so a empty annotation file was generated. 
You may need to check the file structure of your uploaded `.zip` file, it should be a list of folders named by character names. You don't need to put these character named folders into one folder, but you should zip them directly.
Or can you provide a screenshot of your file structure so that I can know the exact problem?

**Comment by sashasubbbb** [comment]
Yeah, it was the problem with folder structure. It was like:
Dataset.zip/Dataset/Voice1
Dataset.zip/Dataset/Voice2

And not:
Dataset.zip/Voice1
Dataset.zip/Voice2

Thank you.
