### ISSUE TITLE
Train locally with error at step 9 "Process all audio data"

### ISSUE THREAD

**Issue by scott870430** [Plachtaa/VITS-fast-fine-tuning#408]
HI, thank you for your awesome work.

I met a error at step 9 when train model locally:

Traceback (most recent call last):
  File "scripts/denoise_audio.py", line 16, in <module>
    wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
  File "/home/xxxx/Documents/VITS/lib/python3.8/site-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
    return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
  File "/home/xxxx/Documents/VITS/lib/python3.8/site-packages/torchaudio/io/_compat.py", line 103, in load_audio
    s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
RuntimeError: Failed to open the input "./separated/htdemucs/77_2/vocals.wav" (No such file or directory).

I already put a long audio under "./raw_audio/", but it show the error above after I run "python3 scripts/denoise_audio.py".

I also try this on colab, but it can work. 
At local space, the folder "separated" hadn't been create.
What I miss when I train locally?
Thank you for your help in advance.

**Comment by anfogy** [comment]
is your voice sample clean enough? if yes simply comment it away using `#`.

**Comment by scott870430** [comment]
I am not sure about that. 
Can I just copy the processed data,  under "separated" folder and segment data, from colab to local?

Or I miss something that make tha "separated" folder didn't be maked?
The different between local and colab is "pyopenjtalk" with generate when installed and the command on colab "%run scripts/vedio2audio.py".
Seem that the command "python3 scripts/vedio2audio.py" on local will not generate "htdemucs" (I have no idea what it is)?

Thank you for your reply.

**Comment by AnyaCoder** [comment]
you need to install a package called demucs
`pip install -U demucs` 
then run the code again.

**Comment by scott870430** [comment]
@AnyaCoder , thanks, it work.
