### ISSUE TITLE
请问如何在原版vits中使用预训练的底模？

### ISSUE THREAD

**Issue by vic233333** [Plachtaa/VITS-fast-fine-tuning#41]
我在其它远程Linux服务器上无法正常部署该项目环境。所以我想直接使用该项目中已有的模型并在此基础上微调。但是配置文件似乎有点问题，一开始训练就会直接覆盖掉原本的预训练模型。
请问如何实现原本vits中的预训练模型微调部署？非常感谢！

**Comment by Plachtaa** [comment]
你说的原版VITS是指这个[多语言版本](https://github.com/CjangCjengh/vits)还是指[原paper的仓库](https://github.com/jaywalnut310/vits)?

**Comment by vic233333** [comment]
> 你说的原版VITS是指这个[多语言版本](https://github.com/CjangCjengh/vits)还是指[原paper的仓库](https://github.com/jaywalnut310/vits)?
是[CjangCjengh的多语言版本](https://github.com/CjangCjengh/vits)

**Comment by Plachtaa** [comment]
这个repo为了适用于微调改了很多东西，具体我也记不清了，不过建议你在debug模式下仔细看一下应该可以找到哪里出了问题
