### ISSUE TITLE
第五步下载不了

### ISSUE THREAD

**Issue by 147graze** [Plachtaa/VITS-fast-fine-tuning#42]
总是显示
python3: can't open file 'rearrange_speaker.py': [Errno 2] No such file or directory
ERROR:root:File `'download_model.py'` not found.

**Comment by 147graze** [comment]
请问这样该怎么办

**Comment by Plachtaa** [comment]
刚才又走了一遍流程，没有任何问题。很难判断你碰到了什么异常情况，通用建议是重启笔记本

**Comment by 147graze** [comment]
现在显示无法连接到GPU后端了

**Comment by Plachtaa** [comment]
colab免费额度到了，一天就6小时，等明天刷新再试

**Comment by 147graze** [comment]
谢谢

**Comment by 147graze** [comment]
现在是第三步出错了

**Comment by 147graze** [comment]
AssertionError                            Traceback (most recent call last)
[/content/VITS-fast-fine-tuning/preprocess_v2.py](https://localhost:8080/#) in <module>
     25         if speaker not in speakers:
     26             speakers.append(speaker)
---> 27     assert (len(speakers) != 0), "No audio file found. Please check your uploaded file structure."
     28     # Source 3 (Optional): sampled audios as extra training helpers
     29     if args.add_auxiliary_data:

AssertionError: No audio file found. Please check your uploaded file structure.

**Comment by 147graze** [comment]
请问这是怎么回事？

**Comment by Plachtaa** [comment]
No audio file found. Please check your uploaded file structure.

**Comment by 147graze** [comment]
请问该如何确认

**Comment by 147graze** [comment]
前面步骤都没有出错

**Comment by Plachtaa** [comment]
https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/DATA.MD
