### ISSUE TITLE
RuntimeError: FIND was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Mr47121836** [Plachtaa/VITS-fast-fine-tuning#437]
运行训练的适合报错：
RuntimeError: FIND was unable to find an engine to execute this computation
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/7cda9366-dc76-4525-ab66-a24a83f0f403)

**Comment by AnyaCoder** [comment]
也许是gpu没了

**Comment by anfogy** [comment]
gpu没了就很草

**Comment by Mr47121836** [comment]
> 也许是gpu没了

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/6fe130dd-ee6a-48b8-bf90-c01c541b0ef8)
GPU应该是没问题的

**Comment by anfogy** [comment]
运行`nvidia-smi`和`nvcc --version`所返回的cuda版本是否一致，不一致就下个驱动完善

**Comment by Mr47121836** [comment]
> 

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/e017461b-0648-4a3d-8645-801b1f3a9159)
好像确实不太一样

**Comment by Mr47121836** [comment]
!pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
重新下载torch就可以了

**Comment by anfogy** [comment]
升cuda版本也可以的说（
毕竟你那卡支持cuda11.7

**Comment by Mr47121836** [comment]
> 升cuda版本也可以的说（ 毕竟你那卡支持cuda11.7

应该吧

**Comment by Mr47121836** [comment]
> 没记错的话`nvidia-smi`显示的是driver api，向下兼容的 不过程序嘛，能跑就行

程序和程序员有一个能跑就行:heart:

**Comment by anfogy** [comment]
@LaoLunli 虽然我加载不出你那图，不过试试装个cuda117的torch？

**Comment by 2232141528** [comment]
> !pip install torch==1.12.0+cu113 torchvision==0.13.0+cu113 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113 重新下载torch就可以了

请问下安装太慢了怎么办？

**Comment by Mr47121836** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
