### ISSUE TITLE
关于open_jtalk_dic_utf_8-1.11.tar.gz下载问题

### ISSUE THREAD

**Issue by Mr47121836** [Plachtaa/VITS-fast-fine-tuning#441]
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/aa4244ae-b3d5-4081-90bf-ff95c0ffde61)
对于这种下载速度很慢的情况，可不可以自己下载然后上传到指定的文件夹？
希望有人能帮我！

**Comment by AnyaCoder** [comment]
是的，可以下载好压缩包放在一个地方
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/122108331/bd885394-107f-49a3-88cf-7bdef90daadd)
然后断网，等待报错，定位报错的文件位置，比如第几行说找不到文件，最后把资源的路径改到你放的文件夹位置就可以

**Comment by Mr47121836** [comment]
> 

我这边是远程连接linux服务器的，不太好进行断网操作，我是想下载的压缩包应该会放在一个统一的位置的。但是我还没找出来。&#x1F494;

**Comment by AnyaCoder** [comment]
> > 
> 
> 我这边是远程连接linux服务器的，不太好进行断网操作，我是想下载的压缩包应该会放在一个统一的位置的。但是我还没找出来。💔

我用的也是linux远程服务器，好像我当时ctrl+c就断开了下载，然后它会报一个路径给我，我就去找那个位置改。

**Comment by Mr47121836** [comment]
> > > 
> > 
> > 
> > 我这边是远程连接linux服务器的，不太好进行断网操作，我是想下载的压缩包应该会放在一个统一的位置的。但是我还没找出来。💔
> 
> 我用的也是linux远程服务器，好像我当时ctrl+c就断开了下载，然后它会报一个路径给我，我就去找那个位置改。

明天我试试，谢谢了

**Comment by Mr47121836** [comment]
> > > 
> > 
> > 
> > 我这边是远程连接linux服务器的，不太好进行断网操作，我是想下载的压缩包应该会放在一个统一的位置的。但是我还没找出来。💔
> 
> 我用的也是linux远程服务器，好像我当时ctrl+c就断开了下载，然后它会报一个路径给我，我就去找那个位置改。

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/00518d94-d04e-4622-84cb-c8a7b5a8fbc2)
我还是没有找到他下载包存放的位置

**Comment by Mr47121836** [comment]
> > > 
> > 
> > 
> > 我这边是远程连接linux服务器的，不太好进行断网操作，我是想下载的压缩包应该会放在一个统一的位置的。但是我还没找出来。💔
> 
> 我用的也是linux远程服务器，好像我当时ctrl+c就断开了下载，然后它会报一个路径给我，我就去找那个位置改。

![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/27cf556f-8cb5-41b8-953e-df5e973aeaca)
自己下载好的文件改名之后放到存放的位置，运行程序之后发现他会把我上传的包文件删除，并且进行重新下载！

**Comment by AnyaCoder** [comment]
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/122108331/f6a3e3dc-a12b-411f-9121-28faff278b29)
改一下这个文件里面extract的路径

**Comment by Mr47121836** [comment]
> ![image](https://user-images.githubusercontent.com/122108331/266984536-f6a3e3dc-a12b-411f-9121-28faff278b29.png) 改一下这个文件里面extract的路径，而且那个路径必须是解压之后的文件夹


![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/70fa7ef1-47b2-4631-893d-844de06bde81)
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/ec9daf43-ad81-423f-9319-29fd57849eba)
![image](https://github.com/Plachtaa/VITS-fast-fine-tuning/assets/66686828/00232cc6-99ff-4ade-ac12-c4827cc32aab)
解压后这样就成功了，绷不住了，今天可以下班了&#x1F680;

**Comment by AnyaCoder** [comment]
如果不错的话可以close了 :D
