### ISSUE TITLE
小白發問 關於windows本地訓練環境部署的問題

### ISSUE THREAD

**Issue by RayLei666** [Plachtaa/VITS-fast-fine-tuning#443]
在本地環境部署的step3:
# CUDA 11.7
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
輸入之後產生以下錯誤:
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 2.0.0, 2.0.0+cu117, 2.0.1, 2.0.1+cu117)
ERROR: No matching distribution found for torch==1.13.1+cu117

似乎是pytorch版本不吻合導致，有高手能指點我如何解決嗎

**Comment by AnyaCoder** [comment]
检查一下当前的CUDA版本与所下载版本是否对应
`nvcc -V`
`nvidia-smi`

**Comment by RayLei666** [comment]
> 
nvcc -V 顯示cuda11.7，但 nvdia-smi顯示版本為12.2

C:\Windows\system32>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

C:\Windows\system32>nvidia-smi
Mon Sep 11 17:12:04 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 536.23                 Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080      WDDM  | 00000000:07:00.0  On |                  N/A |
|  0%   47C    P0              40W / 198W |   1106MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |

**Comment by AnyaCoder** [comment]
试试降低nvidia-smi版本到11.7吧？或者把它们都升级到同一个版本: nvcc pytorch nvidia-smi
