### ISSUE TITLE
报错list没有key()的小坑已解决，另外发音和原音想差还是很多是为什么呢？素材不够？

### ISSUE THREAD

**Issue by heiheiheibj** [Plachtaa/VITS-fast-fine-tuning#445]
开始是 cp configs/finetune_speaker.json ./finetune_speaker.json ，一直报错list没有key()
后来发现应当是复制modified_finetune_speaker.json
cp configs/modified_finetune_speaker.json ./finetune_speaker.json

另外我准备训练个郭德纲的，用了40分钟单口相声，训练次数为200，训练完后发音和原音想差还是很多，是素材时长不够还是次数不够呢？

谢谢

**Comment by AnyaCoder** [comment]
重点检查: `final_annotation_train.txt` 两个文件的音频转写情况，停顿和文字是否正确。另外还有就是如果郭子的语速太快了，模型对于音调的学习可能就会有问题。

**Comment by heiheiheibj** [comment]
好嘞

**Comment by scriptboy1990** [comment]
> 重点检查: `final_annotation_train.txt` 两个文件的音频转写情况，停顿和文字是否正确。另外还有就是如果郭子的语速太快了，模型对于音调的学习可能就会有问题。

这个文件全是像日文一样的拼音，能换成看得懂的吗？
