### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#45]
1660Ti 6GB，类似vits项目改batch_size为4勉强能跑，但是这里依然爆显存

然后是一点小建议：
训练的 backend 部分建议这么写
```python
from sys import platform
if platform == "win32":
    backend = 'gloo'
else:
    backend = 'nccl'
dist.init_process_group(backend=backend, init_method='env://', world_size=n_gpus, rank=rank)
```

重采样部分建议拆出来用多进程处理
参考 [resample.py](https://github.com/innnky/so-vits-svc/blob/32k/resample.py)

**Comment by Plachtaa** [comment]
好的，感谢建议！

**Comment by Plachtaa** [comment]
已经merge了这个[pull request](https://github.com/Plachtaa/VITS-fast-fine-tuning/pull/44)
