### ISSUE TITLE
萌新请教一下怎么判断训练情况

### ISSUE THREAD

**Issue by Wenbobobo** [Plachtaa/VITS-fast-fine-tuning#47]
文档中提到** “根据声线和样本质量的不同，所需的训练epochs数也不同。但是一般建议设置为30 epochs。你也可以在Tensorboard中预览合成效果，若效果满意可提前停止。”  **
我试着提取了150段短音频和3段长音频，30epochs 之后感觉差点意思，又试着跑了60 epochs，但是跑完了看那几个曲线都还在跳。网上的资料看完一知半解，想请教一下大佬怎么简要地判断模型已经训练完成或者过拟合了？
附我的例子
![image](https://user-images.githubusercontent.com/78262508/222464347-62c6d577-775d-4255-b6b0-4233d8dfbd66.png)
![image](https://user-images.githubusercontent.com/78262508/222464504-677aaf8f-bbcf-42ce-92f1-01977bc56708.png)
![image](https://user-images.githubusercontent.com/78262508/222464467-3bad77dd-3b51-46f2-8d15-5478960b9701.png)

**Comment by Plachtaa** [comment]
这个从loss很难看出来效果如何。不过你可以在./OUTPUT_MODEL/里找到很多名叫G_*.pth的文件，它们代表训练中途保存的各个检查点。你可以先跑一个比较长的训练，之后每个都试一次，找其中那个效果最好的保存就行。
