### ISSUE TITLE
笔记本Step3重复报错

### ISSUE THREAD

**Issue by Qianquqwq** [Plachtaa/VITS-fast-fine-tuning#490]
使用作者的笔记本，在Step3开始时一定会报错，修改样本和模型类型依然复现
error: XDG_RUNTIME_DIR not set in the environment.
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default

**Comment by shiyun535** [comment]
遇到了同样的问题，使用ZIP文件上传短音频处理，到step3时报错。
Warning: no long audios & videos found, this IS expected if you have only uploaded short audios
this IS NOT expected if you have uploaded any long audios, videos or video links. Please check your file structure or make sure your audio/video language is supported.
/usr/local/lib/python3.10/dist-packages/whisper/timing.py:57: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def backtrace(trace: np.ndarray):
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.

**Comment by Ciel171** [comment]
同样的问题，不论在COLAB 还是在本地ANACONDA运行都会遇到这个问题

**Comment by NH19-22** [comment]
同样的问题，前天还在colab上训练成功了，今天就报错了

**Comment by John-Aldrich** [comment]
+1同问

**Comment by NH19-22** [comment]
兄弟们，我摸索出来了，install requirements.txt之前，把requirements.txt文件里面的torchaudio改成torchaudio==0.11.0
colab我成功了，win没有测试

**Comment by Plachtaa** [comment]
问题已经修复，原因是`openai-whisper`库的pip源有问题，更换为openai的GitHub源之后可以正常transcribe
