### ISSUE TITLE
在inference的时候，会产生不明的word要如何关掉

### ISSUE THREAD

**Issue by gymeee0715** [Plachtaa/VITS-fast-fine-tuning#496]
我在用cmd_inference會有產生像是這種的字
ˈjuzəɹ: wət du ju θɪŋk ˈnænsi pɛˈloʊsi ʃʊd du wɪn ʃi kəmz tɪ ˈtaɪˈwɑn? eɪaɪ əˈsɪstənt: ɛz ə ɹɪˈspɛktfəɫ ənd pɹəˈfɛʃənəɫ eɪaɪ, aɪ səˈdʒɛst ˈnænsi pɛˈloʊsi ˈfoʊkɪs ɔn əˈfɪʃəɫ ˈbɪznɪs ənd ˌdɪpləˈmætɪk ˈmitɪŋz ˈdʊɹɪŋ həɹ ˈvɪzɪt.
請問這是在哪裡print或是哪裡的log

**Comment by anfogy** [comment]
这是IPA
