### ISSUE TITLE
【期望】Linux版的语音合成，提供API

### ISSUE THREAD

**Issue by Ikaros-521** [Plachtaa/VITS-fast-fine-tuning#5]
期望如图
![6_}(MU~D9BV4F9S~ WU`9PM](https://user-images.githubusercontent.com/40910637/219940510-aa9eedca-cc38-43ba-938d-a97b6e023ce6.png)

**Comment by Plachtaa** [comment]
都用上Linux了，想必装个python环境直接运行VC_inference.py也不在话下罢
API显然是相当困难的，因为咱没钱运营服务器（悲）

**Comment by Ikaros-521** [comment]
> 都用上Linux了，想必装个python环境直接运行VC_inference.py也不在话下罢 API显然是相当困难的，因为咱没钱运营服务器（悲）

感谢，没看到VC_inference.py，那就问题不大了。
