### ISSUE TITLE
请教一下为什么到训练这一步会报错

### ISSUE THREAD

**Issue by Lawrance1106** [Plachtaa/VITS-fast-fine-tuning#50]
提示ZeroDivisionError: integer division or modulo by zero
之前成功过一次，后来再试就一直报这个错误

**Comment by Plachtaa** [comment]
样本太少或者说话人只有一个的时候采样器有概率抽风，修正一下样本就可以了

**Comment by Lawrance1106** [comment]
好的，谢谢，刚刚通过把CJ预训练模型换成CJE已经可以运行了，感谢解答
