### ISSUE TITLE
相比于原始的vits，这个算法在fast fine tune这块针对模型做了哪些改动

### ISSUE THREAD

**Issue by scriptboy1990** [Plachtaa/VITS-fast-fine-tuning#513]

**Comment by scriptboy1990** [comment]
> 没有改动

喔，意思是原始的vits就支持几十秒的声音就可以克隆吗。

**Comment by KdaiP** [comment]
> > 没有改动
> 
> 喔，意思是原始的vits就支持几十秒的声音就可以克隆吗。

克隆主要看底模的能力，底模数据和多样性大克隆的效果就好。如果在原版Vits上更换一个支持多语种的文本前端然后用大量数据训练一个底模出来效果也会很好的。
这个repo除了模型以外的改动还挺多的，比如更方便的数据处理，更少的报错等等，原版Vits坑很多，这个部署起来容易多了。

**Comment by scriptboy1990** [comment]
克隆一般是在多说话人的底模上微调吗。

**Comment by KdaiP** [comment]
> 克隆一般是在多说话人的底模上微调吗。

是的。所以在[LOCAL.md](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/LOCAL.md)里面有一个步骤就是下载和加载底模。

**Comment by scriptboy1990** [comment]
> > 克隆一般是在多说话人的底模上微调吗。
> 
> 是的。所以在[LOCAL.md](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/LOCAL.md)里面有一个步骤就是下载和加载底模。

CJE，CJ，C那几个那肯定也是多说话人的底模咯！
意思是只要训练底模的数据越多，模型越鲁棒，用于克隆的新语音数据可能就越短！
