### ISSUE TITLE
纯推理的运行需求

### ISSUE THREAD

**Issue by prometheus-alien** [Plachtaa/VITS-fast-fine-tuning#552]
可不用考虑cuda版本，我本地cuda11.1推理没问题。
`# 克隆库
git clone https://github.com/Plachtaa/VITS-fast-fine-tuning.git

# 运行requirement
cd VITS-fast-fine-tuning
pip install -r requirements.txt

# Build monotonic align 
cd monotonic_align
mkdir monotonic_align
python setup.py build_ext --inplace
cd ..

# NumPy需要1.22以上
# 如果已安装1.22以下版本先卸载或者用新的虚拟环境
pip uninstall numpy
pip install numpy==1.22
# 或
pip install numpy==1.23 `

# 命令行运行
python cmd_inference.py -m /home/Download/vits_model/Lisi/G_latest.pth -c /home/Download/vits_model/Lisi/config.json -o /home/Download/vits_result -l "简体中文" -t "轻轻的我走了，
正如我轻轻的来；
我轻轻的招手，
作别西天的云彩。" -s "Lisi" -ls 0.9  -on "李四_测试_语速0.9_2023-12-14"

**Comment by LiaoYujia** [comment]
你好，想问问cuda11.1 能够训练不？

**Comment by prometheus-alien** [comment]
> 你好，想问问cuda11.1 能够训练不？

不记得了 这个项目挺久没用了
