### ISSUE TITLE
步骤3的问题

### ISSUE THREAD

**Issue by Game5048-bilibili** [Plachtaa/VITS-fast-fine-tuning#58]
<img width="960" alt="屏幕截图 2023-03-05 120936" src="https://user-images.githubusercontent.com/78400610/222941303-28db396a-c6d4-4c83-a55b-db8a3178ae4a.png">

不知道怎么办qwq

**Comment by Plachtaa** [comment]
![issu3](https://user-images.githubusercontent.com/112609742/222944491-33ba3fdd-746f-42e8-95df-83f4b3ad4910.png)
建议检查一下上传之后的文件结构是否如图所示，还有就是单个视频最好不要超过20分钟，不然会爆显存导致后续无法正常进行

**Comment by Game5048-bilibili** [comment]
好的谢谢
