### ISSUE TITLE
建议多线程下载视频

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#59]
逻辑比较简单就不发pr了
```python
import os
import random
import shutil
from concurrent.futures import ThreadPoolExecutor
from google.colab import files

basepath = os.getcwd()
uploaded = files.upload()  # 上传文件
for filename in uploaded.keys():
    assert (filename.endswith(".txt")), "speaker-videolink info could only be .txt file!"
    shutil.move(os.path.join(basepath, filename), os.path.join("./speaker_links.txt"))


def generate_infos():
    infos = []
    with open("./speaker_links.txt", 'r', encoding='utf-8') as f:
        lines = f.readlines()
    for line in lines:
        line = line.replace("\n", "").replace(" ", "")
        if line == "":
            continue
        speaker, link = line.split("|")
        filename = speaker + "_" + str(random.randint(0, 1000000))
        infos.append({"link": link, "filename": filename})
    return infos


def download_video(info):
    link = info["link"]
    filename = info["filename"]
    os.system(f"youtube-dl -f 0 {link} -o ./video_data/{filename}.mp4")


if __name__ == "__main__":
    infos = generate_infos()
    with ThreadPoolExecutor(max_workers=os.cpu_count() - 2) as executor:
        executor.map(download_video, infos)
```

![image](https://user-images.githubusercontent.com/42791572/222945172-d51c7fb0-d08b-4ab5-83f6-328f2ffd9c5c.png)

**Comment by eve2ptp** [comment]
video2audio.py 同理

**Comment by Plachtaa** [comment]
感谢建议！不过其实我没怎么用过多线程库，大佬还是发下pr吧，onegaishimasu🙏

**Comment by eve2ptp** [comment]
> 感谢建议！不过其实我没怎么用过多线程库，大佬还是发下pr吧，onegaishimasu🙏

我刚测试发现 denoise_audio.py 不控制线程数的话会爆显存，这一块会写注释。进程池两个 worker 没问题，colab或许可以高一点。

一会发pr，到时候你再跑一遍流程测试没问题就行。

**Comment by eve2ptp** [comment]
然后 long_audio_transcribe.py 和 short_audio_transcribe.py 写的有点杂（
一会我看看怎么改比较合适

**Comment by Plachtaa** [comment]
> > 感谢建议！不过其实我没怎么用过多线程库，大佬还是发下pr吧，onegaishimasu🙏
> 
> 我刚测试发现 denoise_audio.py 不控制线程数的话会爆显存，这一块会写注释。进程池两个 worker 没问题，colab或许可以高一点。
> 
> 三个worker的比较吃内存 ![snipaste_20230305_144724](https://user-images.githubusercontent.com/42791572/222946071-4ed2b1ad-71ea-4327-bd4f-0337473573fe.png)
> 
> 一会发pr，到时候你再跑一遍流程测试没问题就行。

denoise_audio.py这个我看了一下还是最好不要多线程，因为demucs处理音频的时候使用的显存和音频长度是正相关的，一般超过20分钟的就会爆显存了，弄成多workers可能会导致可处理的音频长度上限变短
另外两个测试完没问题就会merge。感谢大佬的贡献！

**Comment by eve2ptp** [comment]
os.cpu_count()是下午处理denoise的时候把多进程弄混了
多线程那块开8个worker没问题的，爬虫上百个线程都能开
![image](https://user-images.githubusercontent.com/42791572/222961835-9b4e16d3-8e03-4c24-ab9c-74cdff172790.png)
