### ISSUE TITLE
Colab 步骤4~5 错误代码

### ISSUE THREAD

**Issue by water891215** [Plachtaa/VITS-fast-fine-tuning#6]
![3](https://user-images.githubusercontent.com/106437697/219944290-d949d9cf-546c-48c1-9692-81a2160702df.png)
![2 (2)](https://user-images.githubusercontent.com/106437697/219944292-8e067199-790b-483f-b43b-bf8f09568ce6.png)
![1](https://user-images.githubusercontent.com/106437697/219944296-075e029d-360f-4c22-afe6-8a50d727107c.png)

**Comment by Plachtaa** [comment]
这是因为第四步的时候程序拿到的标注文件是空的，所以报错后自动结束了，也就不会生成一个G_latest.pth供第五步使用。
关于标注文件为什么是空的，如果你是上传的自己的压缩文件，那么很可能是文件结构不对，导致一条语音也没有读到；
如果你是录入的自己的声音，那么录完一句之后记得点一下save audio那个按钮
