### ISSUE TITLE
能否针对长文本切片推理再合成

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#63]
虽然b站弹幕限制30个字，但是鉴于国内丐版学生机|Azure石头盘|甚至树莓派**羸弱的cpu性能**，超过20字推理就会变得奇慢。
或者说以[快速推理的思路](https://github.com/innnky/MB-iSTFT-VITS)重写这部分函数（针对已有模型仅推理用）
```python
with no_grad():
    x_tst = stn_tst.unsqueeze(0).to(device)
    x_tst_lengths = LongTensor([stn_tst.size(0)]).to(device)
    sid = LongTensor([speaker_id]).to(device)
    audio = model.infer(x_tst, x_tst_lengths, sid=sid, noise_scale=.667, noise_scale_w=0.8, length_scale=1.0 / speed)[0][0, 0].data.cpu().float().numpy()
```

**Comment by Plachtaa** [comment]
因为训练数据基本上也都很短，所以长文本推理不仅慢，而且效果也会差很多，所以不推荐直接输入长文本进行推理。我记得sovits的开发者还写过一个长文本推理工具，反正是把长文本自动切片之后推理就可以了。

**Comment by eve2ptp** [comment]
> 因为训练数据基本上也都很短，所以长文本推理不仅慢，而且效果也会差很多，所以不推荐直接输入长文本进行推理。我记得sovits的开发者还写过一个长文本推理工具，反正是把长文本自动切片之后推理就可以了。

flask做后端，弹幕一多会阻塞在推理这里，下一个请求要等上一个生成完才能继续处理
用async/await处理推理部分是否可行

**Comment by eve2ptp** [comment]
还有个奇怪的问题
```python
for clip in segmented_text:
    ......
    audio = net_g.infer()
    lst.append(audio)

merge_audio = np.hstack(lst)
```
分段推理出来的结果转语音会变成等分断句而不是整句，求解

**Comment by Plachtaa** [comment]
不太清楚，我也没用过这个功能。

**Comment by eve2ptp** [comment]
> 不太清楚，我也没用过这个功能。不过不太懂你说的分断句是什么意思，是说完整的句子被劈开了听起来很不自然吗？

"文本切割测试：今日云天晴，微风拂面"
我把它拆成两段来推理
"文本切割测试：今日多"
"云天晴，微风拂面"

推理完再合并audio对象，读出来就是两段的

**Comment by Plachtaa** [comment]
这只能说切文本切得太烂了吧🤣按句号切肯定会好一些

**Comment by eve2ptp** [comment]
确实，怎么简单怎么来
```python
split_text = re.split('[：，。！,.!]', clean_text)
```
