### ISSUE TITLE
关于抓取B站视频的一点想法

### ISSUE THREAD

**Issue by yanfeiwong** [Plachtaa/VITS-fast-fine-tuning#70]
B站本身的自动字幕识别效果好像比whisper识别的要好不少，而且分段也更好的样子，是不是可以考虑直接抓取那个？类似于这个视频里这样https://www.bilibili.com/video/BV1Yv4y117u2。
另外有一些cc字幕可能也不错..
然后现在的分段是不是也有点问题，会切出来很小的文件，有标注但几乎没声音，断句也不太好，就导致最后训练出来的模型处理短句子和结尾的效果都一般般？

**Comment by yanfeiwong** [comment]
而且whisper比较有特色....一些内容可能直接自动就从外语翻译成中文了....

**Comment by Plachtaa** [comment]
whisper切片原本确实问题很大，就像你说的那样，经常切得牛头不对马嘴，但是印象中后来改了一下参数就正常了，原来还是不行吗......我再检查一下，感谢提醒

**Comment by yanfeiwong** [comment]
> 

https://post.smzdm.com/p/all4qx88/看看能不能参考这个文章里的做法，b站抓回来的AI字幕应该更靠谱一些
```
{
      "from": 132.72,
      "to": 138.75,
      "sid": 65,
      "location": 2,
      "content": "所有人都看见一道亮光从天空中划过",
      "music": 0.0
    },
```

**Comment by Plachtaa** [comment]
解决了，必须用large才行，medium切的有问题

**Comment by yanfeiwong** [comment]
> 解决了，必须用large才行，medium切的有问题

large和largeV2实际上也会抽风...概率低一些

**Comment by Plachtaa** [comment]
> > 
> 
> [https://post.smzdm.com/p/all4qx88/看看能不能参考这个文章里的做法，b站抓回来的AI字幕应该更靠谱一些](https://post.smzdm.com/p/all4qx88/%E7%9C%8B%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%E6%96%87%E7%AB%A0%E9%87%8C%E7%9A%84%E5%81%9A%E6%B3%95%EF%BC%8Cb%E7%AB%99%E6%8A%93%E5%9B%9E%E6%9D%A5%E7%9A%84AI%E5%AD%97%E5%B9%95%E5%BA%94%E8%AF%A5%E6%9B%B4%E9%9D%A0%E8%B0%B1%E4%B8%80%E4%BA%9B)
> 
> ```
> {
>       "from": 132.72,
>       "to": 138.75,
>       "sid": 65,
>       "location": 2,
>       "content": "所有人都看见一道亮光从天空中划过",
>       "music": 0.0
>     },
> ```

感谢你提供的方案，这个看起来确实很不错，但是说实话我没那么多空余时间研究了，剩下的精力只够做做收尾工作😥

**Comment by yanfeiwong** [comment]
> > > 
> > 
> > 
> > [https://post.smzdm.com/p/all4qx88/看看能不能参考这个文章里的做法，b站抓回来的AI字幕应该更靠谱一些](https://post.smzdm.com/p/all4qx88/%E7%9C%8B%E7%9C%8B%E8%83%BD%E4%B8%8D%E8%83%BD%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%E6%96%87%E7%AB%A0%E9%87%8C%E7%9A%84%E5%81%9A%E6%B3%95%EF%BC%8Cb%E7%AB%99%E6%8A%93%E5%9B%9E%E6%9D%A5%E7%9A%84AI%E5%AD%97%E5%B9%95%E5%BA%94%E8%AF%A5%E6%9B%B4%E9%9D%A0%E8%B0%B1%E4%B8%80%E4%BA%9B)
> > ```
> > {
> >       "from": 132.72,
> >       "to": 138.75,
> >       "sid": 65,
> >       "location": 2,
> >       "content": "所有人都看见一道亮光从天空中划过",
> >       "music": 0.0
> >     },
> > ```
> 
> 感谢你提供的方案，这个看起来确实很不错，但是说实话我没那么多空余时间研究了，剩下的精力只够做做收尾工作😥

好吧，谢谢你了，加油！
