### ISSUE TITLE
步骤三的第二个步骤报错

### ISSUE THREAD

**Issue by 2282908454** [Plachtaa/VITS-fast-fine-tuning#74]
[](url)
![image](https://user-images.githubusercontent.com/127122311/223145258-8b17d398-459f-4d72-8fb0-a474b24eae20.png)

**Comment by Plachtaa** [comment]
你传的什么文件？

**Comment by 2282908454** [comment]
> 你传的什么文件？
b站的视频链接，写在文本文档里就上传了
[新建文本文档.txt](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10905519/default.txt)

**Comment by Plachtaa** [comment]
[default.txt](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10905560/default.txt)
你得把后面那串删了才能下载下来

**Comment by 2282908454** [comment]
> [default.txt](https://github.com/Plachtaa/VITS-fast-fine-tuning/files/10905560/default.txt) 你得把后面那串删了才能下载下来
步骤4跑了半小时，出现这样的界面，Tensorboard用不了，下面的尝试效果步骤也用不了了
![Snipaste_2023-03-07_14-02-36](https://user-images.githubusercontent.com/127122311/223342520-e57a3059-2fe9-4cba-bd4c-5a97f0b31e66.png)

**Comment by Plachtaa** [comment]
这是因为你断开连接之后又重连了，训练还是在正常进行的
