### ISSUE TITLE
新模型如何使用之前的赛马娘和原神角色声线呢

### ISSUE THREAD

**Issue by lyfyork** [Plachtaa/VITS-fast-fine-tuning#75]

**Comment by lrioxh** [comment]
换回原来的模型

**Comment by Plachtaa** [comment]
去huggingface下原版模型就行了

**Comment by lyfyork** [comment]
请问是去huggingface单独拿出pretrained_models替换colab中的吗，还有其他需要替换的吗
目前手边没有设备，暂时没办法实际去看

**Comment by lyfyork** [comment]
ok，感谢解答，我晚上回去尝试一下

**Comment by lyfyork** [comment]
嗯。。。我希望的是加入其他角色后使用变声器功能，但目前生成模型的配置文件好像只有4个声线？并没有马娘角色和原神角色的选择呢。

**Comment by lyfyork** [comment]
好的 感谢耐心解答
我后续也再试试 
> 手动从[马娘数据集](https://huggingface.co/datasets/Plachta/Umamusume-voice-text-pairs)找对应马娘的音频，当成新角色加入模型。

**Comment by lyfyork** [comment]
关于连续训练我想再请教一下🙏
如果我第一次使用了部分角色训练出一个模型，而后续又想在这个模型基础上添加新的角色声线，目前colab中的脚本支持吗
如果支持的话，我应该怎样做呢

**Comment by Plachtaa** [comment]
这个加入新角色同时保留老角色，原本的实现方式是从老角色的语音里随机抽样几条和新角色混训，不然的话模型会把老角色的声线忘掉。如果你需要这么做的话同样也是推荐把新角色和老角色数据混在一起训练

**Comment by lyfyork** [comment]
最终还是采用了仅训练两个角色用于一对一转化，效果非常不错，非常感谢！

**Comment by yvetteteng** [comment]
你好我想问一下，将旧角色和新角色混训的时候需要注意数据比例吗
