### ISSUE TITLE
#@markdown ### 微调完成后，在这里尝试效果。- 这步报错

### ISSUE THREAD

**Issue by cjd9023** [Plachtaa/VITS-fast-fine-tuning#77]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[/content/VITS-fast-fine-tuning/VC_inference.py](https://localhost:8080/#) in <module>
    128                 upload_audio = gr.Audio(label="or upload audio here", source="upload")
    129                 source_speaker = gr.Dropdown(choices=speakers, value=speakers[0], label="source speaker")
--> 130                 target_speaker = gr.Dropdown(choices=speakers, value=speakers[1], label="target speaker")
    131             with gr.Column():
    132                 message_box = gr.Textbox(label="Message")

IndexError: list index out of range

**Comment by Plachtaa** [comment]
感谢提醒，已修复
