### ISSUE TITLE
Colab 步骤四报错，错误代码

### ISSUE THREAD

**Issue by Molemiki** [Plachtaa/VITS-fast-fine-tuning#8]
进行步骤2，录音后保存，进行步骤2.5时似乎没有处理录音，进行步骤4后出现以下错误
![图片](https://user-images.githubusercontent.com/90849682/220134765-2d808ebf-74bd-4065-a953-5441913b5816.png)
![图片](https://user-images.githubusercontent.com/90849682/220133338-1fc1045d-f86d-4f47-bb13-09b996989780.png)
![图片](https://user-images.githubusercontent.com/90849682/220132324-24a8bc1a-9722-4670-9772-c77440ada15e.png)

**Comment by Plachtaa** [comment]
确认是bug，感谢反馈，正在修复。修复完成后会在这里通知你。

**Comment by Plachtaa** [comment]
刚刚又重新测试了一遍流程，现在步骤2.5应该可以正常处理录音了。

**Comment by Plachtaa** [comment]
录音功能现已移除，在新的pipeline中，直接上传一段3分钟以上阅读任意内容的录音即可，无需切片或标注
