### ISSUE TITLE
请问能不能把whisper的自动识别训练集功能单独做一个项目？

### ISSUE THREAD

**Issue by vic233333** [Plachtaa/VITS-fast-fine-tuning#80]
非常喜欢这个项目的自动识别标注的功能，能不能把这个功能单独分出来，直接输出处理之后的数据集和list？这样我可以在别的vits中（比如[emotional-vits](https://github.com/innnky/emotional-vits)中部署）。

**Comment by Plachtaa** [comment]
那就在笔记本里单独加一个代码块用来下载切片和标注吧，应该不是很难，改好了会在这里告知你。

**Comment by vic233333** [comment]
非常感谢！❤❤❤❤

**Comment by Plachtaa** [comment]
加好了，放在笔记本最底下

**Comment by vic233333** [comment]
> 加好了，放在笔记本最底下

感谢！❤❤❤❤❤
