### ISSUE TITLE
运行步骤3“训练质量”步骤报错

### ISSUE THREAD

**Issue by Iansniper** [Plachtaa/VITS-fast-fine-tuning#81]
> ---------------------------------------------------------------------------
> AssertionError                            Traceback (most recent call last)
> [/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/preprocess_v2.py](https://localhost:8080/#) in <module>
>      31         if speaker not in speakers:
>      32             speakers.append(speaker)
> ---> 33     assert (len(speakers) != 0), "No audio file found. Please check your uploaded file structure."
>      34     # Source 3 (Optional): sampled audios as extra training helpers
>      35     if args.add_auxiliary_data:
> 
> AssertionError: No audio file found. Please check your uploaded file structure.

出现此报错后继续运行步骤4就不会开始训练

> NFO:OUTPUT_MODEL:{'train': {'log_interval': 10, 'eval_interval': 100, 'seed': 1234, 'epochs': 10000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 16, 'fp16_run': True, 'lr_decay': 0.999875, 'segment_size': 8192, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'final_annotation_train.txt', 'validation_files': 'final_annotation_val.txt', 'text_cleaners': ['chinese_cleaners'], 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': True, 'n_speakers': 2, 'cleaned_text': True}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False, 'gin_channels': 256}, 'symbols': ['_', '；', '：', '，', '。', '！', '？', '-', '“', '”', '《', '》', '、', '（', '）', '…', '—', ' ', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '0', 'Ｂ', 'Ｐ'], 'speakers': {'dingzhen': 0, 'taffy': 1}, 'model_dir': '././OUTPUT_MODEL', 'max_epochs': 40, 'drop_speaker_embed': True}
> 2023-03-08 14:56:17.866308: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> DEBUG:tensorflow:Falling back to TensorFlow client; we recommended you install the Cloud TPU client directly with pip install cloud-tpu-client.
> 2023-03-08 14:56:18.844940: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:56:18.845097: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:56:18.845122: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> DEBUG:h5py._conv:Creating converter from 7 to 5
> DEBUG:h5py._conv:Creating converter from 5 to 7
> DEBUG:h5py._conv:Creating converter from 7 to 5
> DEBUG:h5py._conv:Creating converter from 5 to 7
> DEBUG:jaxlib.mlir._mlir_libs:Initializing MLIR with module: _site_initialize_0
> DEBUG:jaxlib.mlir._mlir_libs:Registering dialects from initializer <module 'jaxlib.mlir._mlir_libs._site_initialize_0' from '/usr/local/lib/python3.8/dist-packages/jaxlib/mlir/_mlir_libs/_site_initialize_0.so'>
> DEBUG:jax._src.path:etils.epath found. Using etils.epath for file I/O.
> INFO:numexpr.utils:NumExpr defaulting to 2 threads.
> INFO:torch.distributed.distributed_c10d:Added key: store_based_barrier_key:1 to store for rank: 0
> INFO:torch.distributed.distributed_c10d:Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
> Traceback (most recent call last):
>   File "finetune_speaker_v2.py", line 321, in <module>
>     main()
>   File "finetune_speaker_v2.py", line 55, in main
>     mp.spawn(run, nprocs=n_gpus, args=(n_gpus, hps,))
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 240, in spawn
>     return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
>     while not context.join():
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 160, in join
>     raise ProcessRaisedException(msg, error_index, failed_process.pid)
> torch.multiprocessing.spawn.ProcessRaisedException: 
> 
> -- Process 0 terminated with the following error:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
>     fn(i, *args)
>   File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/finetune_speaker_v2.py", line 73, in run
>     train_dataset = TextAudioSpeakerLoader(hps.data.training_files, hps.data, symbols)
>   File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/data_utils.py", line 24, in __init__
>     self.audiopaths_sid_text = load_filepaths_and_text(audiopaths_sid_text)
>   File "/content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/utils.py", line 276, in load_filepaths_and_text
>     with open(filename, encoding='utf-8') as f:
> FileNotFoundError: [Errno 2] No such file or directory: 'final_annotation_train.txt'

作为参考，上传部分的日志Output

步骤2（全部选择网盘）

2.1 短语音

`Archive:  ./custom_character_voice/custom_character_voice.zip
   creating: ./custom_character_voice/Chara1/
  inflating: ./custom_character_voice/Chara1/Chara1_3星结束行动 (1).wav  
……（共35个文件）  
   creating: ./custom_character_voice/Chara2/
  inflating: ./custom_character_voice/Chara2/Chara2_3星结束行动.wav  
……（共35个文件）  
    `

2.2 长语音

复制了网盘路径跑了代码，没有output，但是在步骤3.1显示上传成功了

2.4 视频链接

`
Chara.txt(text/plain) - 50 bytes, last modified: 2023/3/8 - 100% done
Saving Chara.txt to Chara.txt
Chara_785654.mp4
`

步骤3

3.1 处理上传数据 （134和143结尾的WAV都是前述的长语音文件）

> [MoviePy] Writing audio in ./raw_audio/Chara_78565.wav
> 100%|██████████| 4280/4280 [00:01<00:00, 2189.40it/s][MoviePy] Done.
> 
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_143011.wav
> 100%|████████████████████████████████████████████████████████████████████████| 29.25/29.25 [00:07<00:00,  3.77seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14305.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  6.23seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14301.wav
> 100%|██████████████████████████████████████████████| 35.099999999999994/35.099999999999994 [00:03<00:00, 11.62seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_13472.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  6.12seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_78565.wav
> 100%|██████████████████████████████████████████████| 198.89999999999998/198.89999999999998 [00:10<00:00, 19.62seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14303.wav
> 100%|██████████████████████████████████████████████████████████████████████████| 11.7/11.7 [00:02<00:00,  5.55seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14307.wav
> 100%|██████████████████████████████████████████████████████████████████████████| 23.4/23.4 [00:02<00:00,  8.08seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14304.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  7.59seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14308.wav
> 100%|████████████████████████████████████████████████████████████████████████| 29.25/29.25 [00:02<00:00, 10.38seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_13475.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  7.63seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14306.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  7.59seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_13473.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  6.44seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_13471.wav
> 100%|██████████████████████████████████████████████████████████████████████████| 11.7/11.7 [00:02<00:00,  5.61seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_143012.wav
> 100%|████████████████████████████████████████████████████████████████████████| 29.25/29.25 [00:03<00:00,  8.62seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14302.wav
> 100%|██████████████████████████████████████████████| 35.099999999999994/35.099999999999994 [00:03<00:00, 11.58seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_143010.wav
> 100%|████████████████████████████████████████████████████████████████████████| 29.25/29.25 [00:03<00:00,  8.64seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara2_13474.wav
> 100%|██████████████████████████████████████████████| 17.549999999999997/17.549999999999997 [00:02<00:00,  7.66seconds/s]
> Important: the default model was recently changed to `htdemucs` the latest Hybrid Transformer Demucs model. In some cases, this model can actually perform worse than previous models. To get back the old default model use `-n mdx_extra_q`.
> Selected model is a bag of 1 models. You will see that many progress bars per track.
> Separated tracks will be stored in /content/VITS-fast-fine-tuning/VITS-fast-fine-tuning/VITS-fast-fine-tuning/separated/htdemucs
> Separating track raw_audio/Chara1_14309.wav
> 100%|████████████████████████████████████████████████████████████████████████| 29.25/29.25 [00:03<00:00,  8.70seconds/s]
> Traceback (most recent call last):
>   File "denoise_audio.py", line 12, in <module>
>     wav, sr = torchaudio.load(f"./separated/htdemucs/{file}/vocals.wav", frame_offset=0, num_frames=-1, normalize=True,
>   File "/usr/local/lib/python3.8/dist-packages/torchaudio/backend/sox_io_backend.py", line 246, in load
>     return _fallback_load(filepath, frame_offset, num_frames, normalize, channels_first, format)
>   File "/usr/local/lib/python3.8/dist-packages/torchaudio/io/_compat.py", line 103, in load_audio
>     s = torch.classes.torchaudio.ffmpeg_StreamReader(src, format, None)
> RuntimeError: Failed to open the input "./separated/htdemucs/Chara.txt/vocals.wav" (No such file or directory).
> 2023-03-08 14:53:46.275176: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-03-08 14:53:49.496182: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:53:49.496344: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:53:49.496368: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> ^C
> 2023-03-08 14:54:54.063825: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-03-08 14:54:58.130887: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:54:58.131647: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia
> 2023-03-08 14:54:58.131679: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
> ^C

**Comment by Iansniper** [comment]
此错误可以复现，事实上这是我第二次碰到此问题，第一次我使用本地文件上传，错误信息是一样的。

除此之外，第一次使用并完成训练（40周期）之后，得到的音色与原音色完全不一样，我怀疑训练时程序没有认出我上传的本地文件而使用了sample文件（但是我没保存日志，悲），清空上传文件重新尝试的时候就遇到了上述报错

**Comment by Plachtaa** [comment]
你这是运行了多少遍step1......step1会切换工作路径，如果你运行很多次会导致后面的路径指向也都不对，找不到你的文件大概率也是这个原因导致的

**Comment by Iansniper** [comment]
谢谢，我重新试试看，可能是掉线重连之后我又跑过一次全步骤
