### ISSUE TITLE
请问咱的denoisy是不是写错了路径

### ISSUE THREAD

**Issue by r5rinimaa** [Plachtaa/VITS-fast-fine-tuning#83]

**Comment by r5rinimaa** [comment]
denoisy.py没有运行 直接空运行了

**Comment by r5rinimaa** [comment]
raw_audio_dir = "./raw_audio/"
denoise_audio_dir = "./denoised_audio/"

**Comment by r5rinimaa** [comment]
这个路径是raw_audio 然而我们的录音目录并不是这个路径

**Comment by Plachtaa** [comment]
那你把录音上传到哪里去了呢？事实上这个denoise是只会对长音频和视频运行，短音频是默认干净的，就算真的要对短音频去噪也会很慢

**Comment by r5rinimaa** [comment]
哦哦 根据您的代码 短音频会被传到custom_character_voice 请问有必要去噪吗 慢点就慢点

**Comment by Plachtaa** [comment]
你要是想给短音频去噪就把短音频当成长音频上传就好了，不过就是文件得全部按长音频文件的格式重命名一下

**Comment by r5rinimaa** [comment]
嗯嗯，另外请问colab老是自动断开连接怎么办

**Comment by Plachtaa** [comment]
你只要有单元格在运行的话它是不会自动给你断开的，除非你网或者梯子不太稳定

**Comment by r5rinimaa** [comment]
您好 4090第三步爆显存了 难道4090都不行吗 运行short_audio_transcribe.py 爆显存

**Comment by Plachtaa** [comment]
按理来说是不会的呀，whipser large 显存占用基本上都是10.8GB

**Comment by Plachtaa** [comment]
Close this issue due to long time of no reply
