### ISSUE TITLE
colab训练流程的一些建议

### ISSUE THREAD

**Issue by eve2ptp** [Plachtaa/VITS-fast-fine-tuning#85]
目前issue区99%都是这类**上传数据失败&数据不规范**的错误，实测 colab 输出（debug用）不太明显。

1. README 可以将 DATA.MD 的内容放进去，音频质量和时长要求需加粗标注。

2. 在本地处理完数据源出错的概率远比在线上处理低，只用 data_raw 和 processed_data 处理和保存所有数据比较合理，之后只需要将需要的数据打包上传到 GoogleDrive 解压即可。

3.  [long_audio_transcribe.py](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/long_audio_transcribe.py) 和 [short_audio_transcribe.py](https://github.com/Plachtaa/VITS-fast-fine-tuning/blob/main/short_audio_transcribe.py) 其实都是在做相同的事情，分开写不符合 OOP 原则。 建议合并 long short 的 audio_transcribe 模块，将重采样和转移拆分出来。转译比较耗时，可考虑使用多进程。
- 根据 languages 打标签
- whisper 转译语句
- 输出 file.wav/speaker/translation 到 character_anno.txt

4. STEP 3 的 video2audio 应该放回 STEP 2.4 保证视频都下载完了一并处理。如果视频在下载过程报错或者误以为下载好了点终止 cell，直接跳去 video2audio 必然报错。STEP 3 下载视频的过程用 tqdm 显示出来比较好，后面我加一下。

5. tensorboard 显示 403 或不显示的问题，浏览器允许第三方 cookies，最好在训练前提示。

**Comment by Plachtaa** [comment]
感谢你的建议！
首先whisper转译是不能多进程的，whisper large模型运行需要占用10.8GB显存，colab分配的T4显存只有15GB，至于能不能改转译时的batchsize，以及改了batchsize显存或者内存会不会爆，这个我没试过，你可以试试看；
其次`long_audio_transcribe.py`和`short_audio_transcribe.py`其实是有很大区别的，短音频转译是whisper一句一句进行，长音频是whisper利用长音频的上下文信息进行转译，可以提高转译的准确度，最后处理方式也不一样，短音频是不需要移动位置，长音频需要手动切片之后存到另一个位置，同时保存所有标注。
其它的应该都有提升的空间，不过我最近课业越来越忙了所以这个项目也只能做做收尾工作😥，如果你希望的话我可以把colab notebook的编辑权限开放给你

**Comment by eve2ptp** [comment]
今天疑似遇到bug，第一次训练后关闭笔记本，重新连接后到 STEP3 下载 large-v2.pt 速度骤降。
![image](https://user-images.githubusercontent.com/42791572/224007848-0929c5f6-6fae-4198-928e-ac04ae5b10e9.png)

windows 本地部署存在 .cache里，不知道 colab 能不能预先下载。
