### ISSUE TITLE
Step 3出错

### ISSUE THREAD

**Issue by Eilene90wish** [Plachtaa/VITS-fast-fine-tuning#96]
Warning: no short audios found, this IS expected if you have only uploaded long audios, videos or video links.
this IS NOT expected if you have uploaded a zip file of short audios. Please check your file structure or make sure your audio language is supported.
重新按照说明书上传过几次，视频链接、长视频、长音频最后都会出现这个问题

**Comment by Plachtaa** [comment]
this IS expected if you have only uploaded long audios, videos or video links.
就是说如果你上传的都是视频链接、长视频、长音频，这是EXPECTED的

**Comment by Json0926** [comment]
那如果我短音频也报这个错误要怎么解决呀
